
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>

#define DLSYM(sym, prefix) 	\
    if (strcmp(symbol, #sym) == 0) { \
        extern void* prefix##sym; \
		dbg_print("(dlsym) found symbol %s with handle=%p, address=%p\n", symbol, handle, &prefix##sym); \
        return &prefix##sym; \
    }

static char* dbg;
static char dbg_initualilised = 0;

static void dbg_initilialise(){
	dbg = getenv("DL_DEBUG");
	dbg_initualilised = 1;
}
static void dbg_print(const char *s, ...)
{
	if (dbg_initualilised==0){
		dbg_initilialise();
	}

    if (dbg != NULL)
    {
        va_list args;
        va_start(args, s);
        vfprintf(stderr, s, args);
    }
}

extern void *stub_dlopen(const char *, int);
extern void *stub_dlsym(void *__restrict, const char *__restrict);
extern int stub_dladdr(const void *handle, Dl_info *info);

const char* main_program_handle = "main_program";

const char* lib_libEGL_so_1_libEGL_so = "lib_libEGL_so_1_libEGL_so";
const char* lib_libGLESv2_so_2 = "lib_libGLESv2_so_2";
const char* libwebkitgtkinjectedbundle_so = "libwebkitgtkinjectedbundle_so";
const char* libgiognomeproxy_so = "libgiognomeproxy_so";
const char* libgiognutls_so = "libgiognutls_so";
const char* libgiolibproxy_so = "libgiolibproxy_so";


void* dlopen(const char *path, int mode) {
	if (path == NULL) { return &main_program_handle; }
	if (strcmp( path, "libEGL.so.1" ) == 0) { dbg_print("(dlopen) found library libEGL.so.1 (handle=%p)\n", &lib_libEGL_so_1_libEGL_so); return &lib_libEGL_so_1_libEGL_so; }
	if (strcmp( path, "libEGL.so" ) == 0) { dbg_print("(dlopen) found library libEGL.so (handle=%p)\n", &lib_libEGL_so_1_libEGL_so); return &lib_libEGL_so_1_libEGL_so; }
	if (strcmp( path, "libGLESv2.so.2" ) == 0) { dbg_print("(dlopen) found library libGLESv2.so.2 (handle=%p)\n", &lib_libGLESv2_so_2); return &lib_libGLESv2_so_2; }
	if (strcmp( path, "/usr/lib/webkitgtk-6.0/injected-bundle/libwebkitgtkinjectedbundle.so" ) == 0) { dbg_print("(dlopen) found library /usr/lib/webkitgtk-6.0/injected-bundle/libwebkitgtkinjectedbundle.so (handle=%p)\n", &libwebkitgtkinjectedbundle_so); return &libwebkitgtkinjectedbundle_so; }
	if (strcmp( path, "/usr/lib/gio/modules/libgiognomeproxy.so" ) == 0) { dbg_print("(epiphany dlopen) found library /usr/lib/gio/modules/libgiognomeproxy.so (handle=%p)\n", &libgiognomeproxy_so); return &libgiognomeproxy_so; }
	if (strcmp( path, "/usr/lib/gio/modules/libgiognutls.so" ) == 0) { dbg_print("(epiphany dlopen) found library /usr/lib/gio/modules/libgiognutls.so (handle=%p)\n", &libgiognutls_so); return &libgiognutls_so; }
	if (strcmp( path, "/usr/lib/gio/modules/libgiolibproxy.so" ) == 0) { dbg_print("(epiphany dlopen) found library /usr/lib/gio/modules/libgiolibproxy.so (handle=%p)\n", &libgiolibproxy_so); return &libgiolibproxy_so; }

	fprintf(stderr, "(dlopen) WARNING: failed for path %s\n", path);	return stub_dlopen(path, mode);
}

void* dlsym(void *__restrict handle, const char *__restrict symbol) {

	if (handle == &lib_libEGL_so_1_libEGL_so || handle == NULL || handle == &main_program_handle) { 
		DLSYM(eglBindAPI, )
		DLSYM(eglBindTexImage, )
		DLSYM(eglChooseConfig, )
		DLSYM(eglClientWaitSync, )
		DLSYM(eglCopyBuffers, )
		DLSYM(eglCreateContext, )
		DLSYM(eglCreateImage, )
		DLSYM(eglCreatePbufferFromClientBuffer, )
		DLSYM(eglCreatePbufferSurface, )
		DLSYM(eglCreatePixmapSurface, )
		DLSYM(eglCreatePlatformPixmapSurface, )
		DLSYM(eglCreatePlatformWindowSurface, )
		DLSYM(eglCreateSync, )
		DLSYM(eglCreateWindowSurface, )
		DLSYM(eglDestroyContext, )
		DLSYM(eglDestroyImage, )
		DLSYM(eglDestroySurface, )
		DLSYM(eglDestroySync, )
		DLSYM(eglGetConfigAttrib, )
		DLSYM(eglGetConfigs, )
		DLSYM(eglGetCurrentContext, )
		DLSYM(eglGetCurrentDisplay, )
		DLSYM(eglGetCurrentSurface, )
		DLSYM(eglGetDisplay, )
		DLSYM(eglGetError, )
		DLSYM(eglGetPlatformDisplay, )
		DLSYM(eglGetProcAddress, )
		DLSYM(eglGetSyncAttrib, )
		DLSYM(eglInitialize, )
		DLSYM(eglMakeCurrent, )
		DLSYM(eglQueryAPI, )
		DLSYM(eglQueryContext, )
		DLSYM(eglQueryString, )
		DLSYM(eglQuerySurface, )
		DLSYM(eglReleaseTexImage, )
		DLSYM(eglReleaseThread, )
		DLSYM(eglSurfaceAttrib, )
		DLSYM(eglSwapBuffers, )
		DLSYM(eglSwapInterval, )
		DLSYM(eglTerminate, )
		DLSYM(eglWaitClient, )
		DLSYM(eglWaitGL, )
		DLSYM(eglWaitNative, )
		DLSYM(eglWaitSync, )
	}


	if (handle == &lib_libGLESv2_so_2 || handle == NULL || handle == &main_program_handle) { 
		DLSYM(glActiveShaderProgram, )
		DLSYM(glActiveTexture, )
		DLSYM(glAttachShader, )
		DLSYM(glBeginQuery, )
		DLSYM(glBeginTransformFeedback, )
		DLSYM(glBindAttribLocation, )
		DLSYM(glBindBuffer, )
		DLSYM(glBindBufferBase, )
		DLSYM(glBindBufferRange, )
		DLSYM(glBindFramebuffer, )
		DLSYM(glBindImageTexture, )
		DLSYM(glBindProgramPipeline, )
		DLSYM(glBindRenderbuffer, )
		DLSYM(glBindSampler, )
		DLSYM(glBindTexture, )
		DLSYM(glBindTransformFeedback, )
		DLSYM(glBindVertexArray, )
		DLSYM(glBindVertexBuffer, )
		DLSYM(glBlendBarrier, )
		DLSYM(glBlendColor, )
		DLSYM(glBlendEquation, )
		DLSYM(glBlendEquationSeparate, )
		DLSYM(glBlendEquationSeparatei, )
		DLSYM(glBlendEquationi, )
		DLSYM(glBlendFunc, )
		DLSYM(glBlendFuncSeparate, )
		DLSYM(glBlendFuncSeparatei, )
		DLSYM(glBlendFunci, )
		DLSYM(glBlitFramebuffer, )
		DLSYM(glBufferData, )
		DLSYM(glBufferSubData, )
		DLSYM(glCheckFramebufferStatus, )
		DLSYM(glClear, )
		DLSYM(glClearBufferfi, )
		DLSYM(glClearBufferfv, )
		DLSYM(glClearBufferiv, )
		DLSYM(glClearBufferuiv, )
		DLSYM(glClearColor, )
		DLSYM(glClearDepthf, )
		DLSYM(glClearStencil, )
		DLSYM(glClientWaitSync, )
		DLSYM(glColorMask, )
		DLSYM(glColorMaski, )
		DLSYM(glCompileShader, )
		DLSYM(glCompressedTexImage2D, )
		DLSYM(glCompressedTexImage3D, )
		DLSYM(glCompressedTexSubImage2D, )
		DLSYM(glCompressedTexSubImage3D, )
		DLSYM(glCopyBufferSubData, )
		DLSYM(glCopyImageSubData, )
		DLSYM(glCopyTexImage2D, )
		DLSYM(glCopyTexSubImage2D, )
		DLSYM(glCopyTexSubImage3D, )
		DLSYM(glCreateProgram, )
		DLSYM(glCreateShader, )
		DLSYM(glCreateShaderProgramv, )
		DLSYM(glCullFace, )
		DLSYM(glDebugMessageCallback, )
		DLSYM(glDebugMessageControl, )
		DLSYM(glDebugMessageInsert, )
		DLSYM(glDeleteBuffers, )
		DLSYM(glDeleteFramebuffers, )
		DLSYM(glDeleteProgram, )
		DLSYM(glDeleteProgramPipelines, )
		DLSYM(glDeleteQueries, )
		DLSYM(glDeleteRenderbuffers, )
		DLSYM(glDeleteSamplers, )
		DLSYM(glDeleteShader, )
		DLSYM(glDeleteSync, )
		DLSYM(glDeleteTextures, )
		DLSYM(glDeleteTransformFeedbacks, )
		DLSYM(glDeleteVertexArrays, )
		DLSYM(glDepthFunc, )
		DLSYM(glDepthMask, )
		DLSYM(glDepthRangef, )
		DLSYM(glDetachShader, )
		DLSYM(glDisable, )
		DLSYM(glDisableVertexAttribArray, )
		DLSYM(glDisablei, )
		DLSYM(glDispatchCompute, )
		DLSYM(glDispatchComputeIndirect, )
		DLSYM(glDrawArrays, )
		DLSYM(glDrawArraysIndirect, )
		DLSYM(glDrawArraysInstanced, )
		DLSYM(glDrawBuffers, )
		DLSYM(glDrawElements, )
		DLSYM(glDrawElementsBaseVertex, )
		DLSYM(glDrawElementsIndirect, )
		DLSYM(glDrawElementsInstanced, )
		DLSYM(glDrawElementsInstancedBaseVertex, )
		DLSYM(glDrawRangeElements, )
		DLSYM(glDrawRangeElementsBaseVertex, )
		DLSYM(glEnable, )
		DLSYM(glEnableVertexAttribArray, )
		DLSYM(glEnablei, )
		DLSYM(glEndQuery, )
		DLSYM(glEndTransformFeedback, )
		DLSYM(glFenceSync, )
		DLSYM(glFinish, )
		DLSYM(glFlush, )
		DLSYM(glFlushMappedBufferRange, )
		DLSYM(glFramebufferParameteri, )
		DLSYM(glFramebufferRenderbuffer, )
		DLSYM(glFramebufferTexture, )
		DLSYM(glFramebufferTexture2D, )
		DLSYM(glFramebufferTextureLayer, )
		DLSYM(glFrontFace, )
		DLSYM(glGenBuffers, )
		DLSYM(glGenFramebuffers, )
		DLSYM(glGenProgramPipelines, )
		DLSYM(glGenQueries, )
		DLSYM(glGenRenderbuffers, )
		DLSYM(glGenSamplers, )
		DLSYM(glGenTextures, )
		DLSYM(glGenTransformFeedbacks, )
		DLSYM(glGenVertexArrays, )
		DLSYM(glGenerateMipmap, )
		DLSYM(glGetActiveAttrib, )
		DLSYM(glGetActiveUniform, )
		DLSYM(glGetActiveUniformBlockName, )
		DLSYM(glGetActiveUniformBlockiv, )
		DLSYM(glGetActiveUniformsiv, )
		DLSYM(glGetAttachedShaders, )
		DLSYM(glGetAttribLocation, )
		DLSYM(glGetBooleani_v, )
		DLSYM(glGetBooleanv, )
		DLSYM(glGetBufferParameteri64v, )
		DLSYM(glGetBufferParameteriv, )
		DLSYM(glGetBufferPointerv, )
		DLSYM(glGetDebugMessageLog, )
		DLSYM(glGetError, )
		DLSYM(glGetFloatv, )
		DLSYM(glGetFragDataLocation, )
		DLSYM(glGetFramebufferAttachmentParameteriv, )
		DLSYM(glGetFramebufferParameteriv, )
		DLSYM(glGetGraphicsResetStatus, )
		DLSYM(glGetInteger64i_v, )
		DLSYM(glGetInteger64v, )
		DLSYM(glGetIntegeri_v, )
		DLSYM(glGetIntegerv, )
		DLSYM(glGetInternalformativ, )
		DLSYM(glGetMultisamplefv, )
		DLSYM(glGetObjectLabel, )
		DLSYM(glGetObjectPtrLabel, )
		DLSYM(glGetPointerv, )
		DLSYM(glGetProgramBinary, )
		DLSYM(glGetProgramInfoLog, )
		DLSYM(glGetProgramInterfaceiv, )
		DLSYM(glGetProgramPipelineInfoLog, )
		DLSYM(glGetProgramPipelineiv, )
		DLSYM(glGetProgramResourceIndex, )
		DLSYM(glGetProgramResourceLocation, )
		DLSYM(glGetProgramResourceName, )
		DLSYM(glGetProgramResourceiv, )
		DLSYM(glGetProgramiv, )
		DLSYM(glGetQueryObjectuiv, )
		DLSYM(glGetQueryiv, )
		DLSYM(glGetRenderbufferParameteriv, )
		DLSYM(glGetSamplerParameterIiv, )
		DLSYM(glGetSamplerParameterIuiv, )
		DLSYM(glGetSamplerParameterfv, )
		DLSYM(glGetSamplerParameteriv, )
		DLSYM(glGetShaderInfoLog, )
		DLSYM(glGetShaderPrecisionFormat, )
		DLSYM(glGetShaderSource, )
		DLSYM(glGetShaderiv, )
		DLSYM(glGetString, )
		DLSYM(glGetStringi, )
		DLSYM(glGetSynciv, )
		DLSYM(glGetTexLevelParameterfv, )
		DLSYM(glGetTexLevelParameteriv, )
		DLSYM(glGetTexParameterIiv, )
		DLSYM(glGetTexParameterIuiv, )
		DLSYM(glGetTexParameterfv, )
		DLSYM(glGetTexParameteriv, )
		DLSYM(glGetTransformFeedbackVarying, )
		DLSYM(glGetUniformBlockIndex, )
		DLSYM(glGetUniformIndices, )
		DLSYM(glGetUniformLocation, )
		DLSYM(glGetUniformfv, )
		DLSYM(glGetUniformiv, )
		DLSYM(glGetUniformuiv, )
		DLSYM(glGetVertexAttribIiv, )
		DLSYM(glGetVertexAttribIuiv, )
		DLSYM(glGetVertexAttribPointerv, )
		DLSYM(glGetVertexAttribfv, )
		DLSYM(glGetVertexAttribiv, )
		DLSYM(glGetnUniformfv, )
		DLSYM(glGetnUniformiv, )
		DLSYM(glGetnUniformuiv, )
		DLSYM(glHint, )
		DLSYM(glInvalidateFramebuffer, )
		DLSYM(glInvalidateSubFramebuffer, )
		DLSYM(glIsBuffer, )
		DLSYM(glIsEnabled, )
		DLSYM(glIsEnabledi, )
		DLSYM(glIsFramebuffer, )
		DLSYM(glIsProgram, )
		DLSYM(glIsProgramPipeline, )
		DLSYM(glIsQuery, )
		DLSYM(glIsRenderbuffer, )
		DLSYM(glIsSampler, )
		DLSYM(glIsShader, )
		DLSYM(glIsSync, )
		DLSYM(glIsTexture, )
		DLSYM(glIsTransformFeedback, )
		DLSYM(glIsVertexArray, )
		DLSYM(glLineWidth, )
		DLSYM(glLinkProgram, )
		DLSYM(glMapBufferRange, )
		DLSYM(glMemoryBarrier, )
		DLSYM(glMemoryBarrierByRegion, )
		DLSYM(glMinSampleShading, )
		DLSYM(glObjectLabel, )
		DLSYM(glObjectPtrLabel, )
		DLSYM(glPatchParameteri, )
		DLSYM(glPauseTransformFeedback, )
		DLSYM(glPixelStorei, )
		DLSYM(glPolygonOffset, )
		DLSYM(glPopDebugGroup, )
		DLSYM(glPrimitiveBoundingBox, )
		DLSYM(glProgramBinary, )
		DLSYM(glProgramParameteri, )
		DLSYM(glProgramUniform1f, )
		DLSYM(glProgramUniform1fv, )
		DLSYM(glProgramUniform1i, )
		DLSYM(glProgramUniform1iv, )
		DLSYM(glProgramUniform1ui, )
		DLSYM(glProgramUniform1uiv, )
		DLSYM(glProgramUniform2f, )
		DLSYM(glProgramUniform2fv, )
		DLSYM(glProgramUniform2i, )
		DLSYM(glProgramUniform2iv, )
		DLSYM(glProgramUniform2ui, )
		DLSYM(glProgramUniform2uiv, )
		DLSYM(glProgramUniform3f, )
		DLSYM(glProgramUniform3fv, )
		DLSYM(glProgramUniform3i, )
		DLSYM(glProgramUniform3iv, )
		DLSYM(glProgramUniform3ui, )
		DLSYM(glProgramUniform3uiv, )
		DLSYM(glProgramUniform4f, )
		DLSYM(glProgramUniform4fv, )
		DLSYM(glProgramUniform4i, )
		DLSYM(glProgramUniform4iv, )
		DLSYM(glProgramUniform4ui, )
		DLSYM(glProgramUniform4uiv, )
		DLSYM(glProgramUniformMatrix2fv, )
		DLSYM(glProgramUniformMatrix2x3fv, )
		DLSYM(glProgramUniformMatrix2x4fv, )
		DLSYM(glProgramUniformMatrix3fv, )
		DLSYM(glProgramUniformMatrix3x2fv, )
		DLSYM(glProgramUniformMatrix3x4fv, )
		DLSYM(glProgramUniformMatrix4fv, )
		DLSYM(glProgramUniformMatrix4x2fv, )
		DLSYM(glProgramUniformMatrix4x3fv, )
		DLSYM(glPushDebugGroup, )
		DLSYM(glReadBuffer, )
		DLSYM(glReadPixels, )
		DLSYM(glReadnPixels, )
		DLSYM(glReleaseShaderCompiler, )
		DLSYM(glRenderbufferStorage, )
		DLSYM(glRenderbufferStorageMultisample, )
		DLSYM(glResumeTransformFeedback, )
		DLSYM(glSampleCoverage, )
		DLSYM(glSampleMaski, )
		DLSYM(glSamplerParameterIiv, )
		DLSYM(glSamplerParameterIuiv, )
		DLSYM(glSamplerParameterf, )
		DLSYM(glSamplerParameterfv, )
		DLSYM(glSamplerParameteri, )
		DLSYM(glSamplerParameteriv, )
		DLSYM(glScissor, )
		DLSYM(glShaderBinary, )
		DLSYM(glShaderSource, )
		DLSYM(glStencilFunc, )
		DLSYM(glStencilFuncSeparate, )
		DLSYM(glStencilMask, )
		DLSYM(glStencilMaskSeparate, )
		DLSYM(glStencilOp, )
		DLSYM(glStencilOpSeparate, )
		DLSYM(glTexBuffer, )
		DLSYM(glTexBufferRange, )
		DLSYM(glTexImage2D, )
		DLSYM(glTexImage3D, )
		DLSYM(glTexParameterIiv, )
		DLSYM(glTexParameterIuiv, )
		DLSYM(glTexParameterf, )
		DLSYM(glTexParameterfv, )
		DLSYM(glTexParameteri, )
		DLSYM(glTexParameteriv, )
		DLSYM(glTexStorage2D, )
		DLSYM(glTexStorage2DMultisample, )
		DLSYM(glTexStorage3D, )
		DLSYM(glTexStorage3DMultisample, )
		DLSYM(glTexSubImage2D, )
		DLSYM(glTexSubImage3D, )
		DLSYM(glTransformFeedbackVaryings, )
		DLSYM(glUniform1f, )
		DLSYM(glUniform1fv, )
		DLSYM(glUniform1i, )
		DLSYM(glUniform1iv, )
		DLSYM(glUniform1ui, )
		DLSYM(glUniform1uiv, )
		DLSYM(glUniform2f, )
		DLSYM(glUniform2fv, )
		DLSYM(glUniform2i, )
		DLSYM(glUniform2iv, )
		DLSYM(glUniform2ui, )
		DLSYM(glUniform2uiv, )
		DLSYM(glUniform3f, )
		DLSYM(glUniform3fv, )
		DLSYM(glUniform3i, )
		DLSYM(glUniform3iv, )
		DLSYM(glUniform3ui, )
		DLSYM(glUniform3uiv, )
		DLSYM(glUniform4f, )
		DLSYM(glUniform4fv, )
		DLSYM(glUniform4i, )
		DLSYM(glUniform4iv, )
		DLSYM(glUniform4ui, )
		DLSYM(glUniform4uiv, )
		DLSYM(glUniformBlockBinding, )
		DLSYM(glUniformMatrix2fv, )
		DLSYM(glUniformMatrix2x3fv, )
		DLSYM(glUniformMatrix2x4fv, )
		DLSYM(glUniformMatrix3fv, )
		DLSYM(glUniformMatrix3x2fv, )
		DLSYM(glUniformMatrix3x4fv, )
		DLSYM(glUniformMatrix4fv, )
		DLSYM(glUniformMatrix4x2fv, )
		DLSYM(glUniformMatrix4x3fv, )
		DLSYM(glUnmapBuffer, )
		DLSYM(glUseProgram, )
		DLSYM(glUseProgramStages, )
		DLSYM(glValidateProgram, )
		DLSYM(glValidateProgramPipeline, )
		DLSYM(glVertexAttrib1f, )
		DLSYM(glVertexAttrib1fv, )
		DLSYM(glVertexAttrib2f, )
		DLSYM(glVertexAttrib2fv, )
		DLSYM(glVertexAttrib3f, )
		DLSYM(glVertexAttrib3fv, )
		DLSYM(glVertexAttrib4f, )
		DLSYM(glVertexAttrib4fv, )
		DLSYM(glVertexAttribBinding, )
		DLSYM(glVertexAttribDivisor, )
		DLSYM(glVertexAttribFormat, )
		DLSYM(glVertexAttribI4i, )
		DLSYM(glVertexAttribI4iv, )
		DLSYM(glVertexAttribI4ui, )
		DLSYM(glVertexAttribI4uiv, )
		DLSYM(glVertexAttribIFormat, )
		DLSYM(glVertexAttribIPointer, )
		DLSYM(glVertexAttribPointer, )
		DLSYM(glVertexBindingDivisor, )
		DLSYM(glViewport, )
		DLSYM(glWaitSync, )
	}


	if (handle == NULL || handle == &libwebkitgtkinjectedbundle_so) { 
		DLSYM(WKBundleInitialize, )

	}
	
	if (handle == NULL || handle == &libgiognomeproxy_so) { 
		DLSYM(g_proxy_resolver_gnome_get_type, )
		DLSYM(g_proxy_resolver_gnome_register, )
		DLSYM(g_io_gnomeproxy_load, )
		DLSYM(g_io_gnomeproxy_query, )
		DLSYM(g_io_gnomeproxy_query, )
	}
	
	if (handle == NULL || handle == &libgiognutls_so) { 
		DLSYM(g_io_gnutls_load, )
		DLSYM(g_io_gnutls_query, )
		DLSYM(g_io_gnutls_unload, )
	}

	if (handle == NULL || handle == &libgiolibproxy_so) { 
		DLSYM(g_libproxy_resolver_get_type, )
		DLSYM(g_libproxy_resolver_register, )
		DLSYM(g_io_libproxy_load, )
		DLSYM(g_io_libproxy_query, )
		DLSYM(g_io_libproxy_unload, )
	}
	
	fprintf(stderr, "(dlsym) WARNING: failed for symbol %s\n", symbol);	return stub_dlsym(handle, symbol);
}


int dladdr(const void *handle, Dl_info *info)
{
    fprintf(stderr, "(dladdr) handle=\"%p\"\n", handle);
    return stub_dladdr(handle, info);
}

