[
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/src/buildtools.git",
      sha256sum = "729495f2ffa69080907780591fa2a630b2556e98",
      fetchMethod = "git"
    },
    dest = "buildtools"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/angle/angle.git",
      sha256sum = "110aa16f60f84c0552edd96fce51684bc0e657b5",
      fetchMethod = "git"
    },
    dest = "third_party/externals/angle2"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/google/brotli.git",
      sha256sum = "6d03dfbedda1615c4cba1211f8d81735575209c8",
      fetchMethod = "git"
    },
    dest = "third_party/externals/brotli"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/GPUOpen-LibrariesAndSDKs/D3D12MemoryAllocator.git",
      sha256sum = "169895d529dfce00390a20e69c2f516066fe7a3b",
      fetchMethod = "git"
    },
    dest = "third_party/externals/d3d12allocator"
  },
  {
    src = {
      uri = "https://dawn.googlesource.com/dawn.git",
      sha256sum = "e78ae5f0450857eb95217ef469fbb173a3cf103d",
      fetchMethod = "git"
    },
    dest = "third_party/externals/dawn"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/src/third_party/abseil-cpp",
      sha256sum = "adabe6e669a66cb842e7a87a08620e486b6276f6",
      fetchMethod = "git"
    },
    dest = "third_party/externals/abseil-cpp"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/src/third_party/jinja2",
      sha256sum = "c3027d884967773057bf74b957e3fea87e5df4d7",
      fetchMethod = "git"
    },
    dest = "third_party/externals/jinja2"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/src/third_party/markupsafe",
      sha256sum = "4256084ae14175d38a3ff7d739dca83ae49ccec6",
      fetchMethod = "git"
    },
    dest = "third_party/externals/markupsafe"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/KhronosGroup/glslang",
      sha256sum = "1d47ffa8ac4374a19b302021e216a20f22a3de92",
      fetchMethod = "git"
    },
    dest = "third_party/externals/glslang"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/webgpu-native/webgpu-headers",
      sha256sum = "706853a9da45b8e89b7ea005aa267294d115f8ce",
      fetchMethod = "git"
    },
    dest = "third_party/externals/webgpu-headers"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/skia-dev/delaunator-cpp.git",
      sha256sum = "98305ef6c4e862f7d48df9cc647b690d796fec68",
      fetchMethod = "git"
    },
    dest = "third_party/externals/delaunator-cpp"
  },
  {
    src = {
      uri = "https://android.googlesource.com/platform/external/dng_sdk.git",
      sha256sum = "dbe0a676450d9b8c71bf00688bb306409b779e90",
      fetchMethod = "git"
    },
    dest = "third_party/externals/dng_sdk"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/KhronosGroup/EGL-Registry",
      sha256sum = "b055c9b483e70ecd57b3cf7204db21f5a06f9ffe",
      fetchMethod = "git"
    },
    dest = "third_party/externals/egl-registry"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/emscripten-core/emsdk.git",
      sha256sum = "c69d433d8509c5c64564c2f0d054bf102a5cf67e",
      fetchMethod = "git"
    },
    dest = "third_party/externals/emsdk"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/libexpat/libexpat.git",
      sha256sum = "8e49998f003d693213b538ef765814c7d21abada",
      fetchMethod = "git"
    },
    dest = "third_party/externals/expat"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/src/third_party/freetype2.git",
      sha256sum = "23b6cd27ff19b70cbf98e058cd2cf0647d5284ff",
      fetchMethod = "git"
    },
    dest = "third_party/externals/freetype"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/harfbuzz/harfbuzz.git",
      sha256sum = "31695252eb6ed25096893aec7f848889dad874bc",
      fetchMethod = "git"
    },
    dest = "third_party/externals/harfbuzz"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/google/highway.git",
      sha256sum = "424360251cdcfc314cfc528f53c872ecd63af0f0",
      fetchMethod = "git"
    },
    dest = "third_party/externals/highway"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/deps/icu.git",
      sha256sum = "364118a1d9da24bb5b770ac3d762ac144d6da5a4",
      fetchMethod = "git"
    },
    dest = "third_party/externals/icu"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/unicode-org/icu4x.git",
      sha256sum = "bcf4f7198d4dc5f3127e84a6ca657c88e7d07a13",
      fetchMethod = "git"
    },
    dest = "third_party/externals/icu4x"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/ocornut/imgui.git",
      sha256sum = "55d35d8387c15bf0cfd71861df67af8cfbda7456",
      fetchMethod = "git"
    },
    dest = "third_party/externals/imgui"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/AOMediaCodec/libavif.git",
      sha256sum = "55aab4ac0607ab651055d354d64c4615cf3d8000",
      fetchMethod = "git"
    },
    dest = "third_party/externals/libavif"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/codecs/libgav1.git",
      sha256sum = "5cf722e659014ebaf2f573a6dd935116d36eadf1",
      fetchMethod = "git"
    },
    dest = "third_party/externals/libgav1"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/FRIGN/libgrapheme/",
      sha256sum = "c0cab63c5300fa12284194fbef57aa2ed62a94c0",
      fetchMethod = "git"
    },
    dest = "third_party/externals/libgrapheme"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/deps/libjpeg_turbo.git",
      sha256sum = "e14cbfaa85529d47f9f55b0f104a579c1061f9ad",
      fetchMethod = "git"
    },
    dest = "third_party/externals/libjpeg-turbo"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/gitlab.com/wg1/jpeg-xl.git",
      sha256sum = "a205468bc5d3a353fb15dae2398a101dff52f2d3",
      fetchMethod = "git"
    },
    dest = "third_party/externals/libjxl"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/third_party/libpng.git",
      sha256sum = "4e3f57d50f552841550a36eabbb3fbcecacb7750",
      fetchMethod = "git"
    },
    dest = "third_party/externals/libpng"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/webm/libwebp.git",
      sha256sum = "845d5476a866141ba35ac133f856fa62f0b7445f",
      fetchMethod = "git"
    },
    dest = "third_party/externals/libwebp"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/libyuv/libyuv.git",
      sha256sum = "d248929c059ff7629a85333699717d7a677d8d96",
      fetchMethod = "git"
    },
    dest = "third_party/externals/libyuv"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/google/oboe.git",
      sha256sum = "b02a12d1dd821118763debec6b83d00a8a0ee419",
      fetchMethod = "git"
    },
    dest = "third_party/externals/oboe"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/KhronosGroup/OpenGL-Registry",
      sha256sum = "14b80ebeab022b2c78f84a573f01028c96075553",
      fetchMethod = "git"
    },
    dest = "third_party/externals/opengl-registry"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/src/base/allocator/partition_allocator.git",
      sha256sum = "ce13777cb731e0a60c606d1741091fd11a0574d7",
      fetchMethod = "git"
    },
    dest = "third_party/externals/partition_alloc"
  },
  {
    src = {
      uri = "https://android.googlesource.com/platform/external/perfetto",
      sha256sum = "93885509be1c9240bc55fa515ceb34811e54a394",
      fetchMethod = "git"
    },
    dest = "third_party/externals/perfetto"
  },
  {
    src = {
      uri = "https://android.googlesource.com/platform/external/piex.git",
      sha256sum = "bb217acdca1cc0c16b704669dd6f91a1b509c406",
      fetchMethod = "git"
    },
    dest = "third_party/externals/piex"
  },
  {
    src = {
      uri = "https://swiftshader.googlesource.com/SwiftShader",
      sha256sum = "5aa3ef64770d6065183b9637fc44065ef7e7566b",
      fetchMethod = "git"
    },
    dest = "third_party/externals/swiftshader"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator",
      sha256sum = "a6bfc237255a6bac1513f7c1ebde6d8aed6b5191",
      fetchMethod = "git"
    },
    dest = "third_party/externals/vulkanmemoryallocator"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/vulkan-deps",
      sha256sum = "446fd082c12124728ca666edb3610b6ca42e0bbc",
      fetchMethod = "git"
    },
    dest = "third_party/externals/vulkan-deps"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/KhronosGroup/SPIRV-Cross",
      sha256sum = "b8fcf307f1f347089e3c46eb4451d27f32ebc8d3",
      fetchMethod = "git"
    },
    dest = "third_party/externals/spirv-cross"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/KhronosGroup/SPIRV-Headers.git",
      sha256sum = "0a7f626a6ae86284a413d105b47a6fb413bf6c92",
      fetchMethod = "git"
    },
    dest = "third_party/externals/spirv-headers"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/KhronosGroup/SPIRV-Tools.git",
      sha256sum = "91ac969ed599bfd0697a5b88cfae550318a04392",
      fetchMethod = "git"
    },
    dest = "third_party/externals/spirv-tools"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/linebender/vello.git",
      sha256sum = "3ee3bea02164c5a816fe6c16ef4e3a810edb7620",
      fetchMethod = "git"
    },
    dest = "third_party/externals/vello"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-Headers",
      sha256sum = "450bd2232225d6c7728a4108055ac2e37cef6475",
      fetchMethod = "git"
    },
    dest = "third_party/externals/vulkan-headers"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-Tools",
      sha256sum = "61c4e7477213bb98ed7299651d6254bc5745e93d",
      fetchMethod = "git"
    },
    dest = "third_party/externals/vulkan-tools"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/KhronosGroup/Vulkan-Utility-Libraries",
      sha256sum = "3e303cbe2bb165887c94d96498eef33b4309b5bd",
      fetchMethod = "git"
    },
    dest = "third_party/externals/vulkan-utility-libraries"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/external/github.com/unicode-org/unicodetools",
      sha256sum = "66a3fa9dbdca3b67053a483d130564eabc5fe095",
      fetchMethod = "git"
    },
    dest = "third_party/externals/unicodetools"
  },
  {
    src = {
      uri = "https://skia.googlesource.com/external/github.com/google/wuffs-mirror-release-c.git",
      sha256sum = "e3f919ccfe3ef542cfc983a82146070258fb57f8",
      fetchMethod = "git"
    },
    dest = "third_party/externals/wuffs"
  },
  {
    src = {
      uri = "https://chromium.googlesource.com/chromium/src/third_party/zlib",
      sha256sum = "646b7f569718921d7d4b5b8e22572ff6c76f2596",
      fetchMethod = "git"
    },
    dest = "third_party/externals/zlib"
  },
]
