{

  # "cosmic-edit" | priority 1 = {
  #   uri = "https://github.com/pop-os/cosmic-edit/archive/refs/tags/epoch-1.0.3.tar.gz",
  #   sha256sum = "72d490b449360f63e4d64a0729be24e1c7e27bb43c0504901e8b4ddf4ec6ccd2"
  # },

  # "cosmic-files" | priority 1 = {
  #   uri = "https://github.com/pop-os/cosmic-files/archive/refs/tags/epoch-1.0.3.tar.gz",
  #   sha256sum = "7f5343200fd342b82f12df22b801285f4f29ba6a1e6f3770e8070f775998fa37"
  # },

  # "cosmic-term" | priority 1 = {
  #   uri = "https://github.com/pop-os/cosmic-term/archive/refs/tags/epoch-1.0.3.tar.gz",
  #   sha256sum = "e5f70a1f34669870ee5dbebe97f184e0a3719a9e18320cdaf436c30d357d4724"
  # },

  # "cosmic-applibrary" | priority 1 = {
  #   uri = "https://github.com/pop-os/cosmic-app-library/archive/1cc22ab57546ebb6699ae26474bd208e6a7c639d.tar.gz",
  #   sha256sum = "a554f305de62a36bdf7ba5cb6743efc9f9e7b4d298f4e2603ed65cf4b976e701",
  # }
}
