{
  "cosmic-applets" = {
    uri = "https://github.com/pop-os/cosmic-applets/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "5d7ce67b2c578d069cbdfb94ac7246462f857f2fc5313ff612fd2d6194e2c948",
  },

  "cosmic-applibrary" = {
    uri = "https://github.com/pop-os/cosmic-applibrary/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "c84741448c8203cb5e9ec566dd318c3082b900f7ee8612d37e94b643a5a243ed",
  },

  "cosmic-bg" = {
    uri = "https://github.com/pop-os/cosmic-bg/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "bbeb2092989d4a7d0aa2abf09068362b8506f44bcb279dbd7633e2de10c6c761",
  },

  "cosmic-comp" = {
    uri = "https://github.com/pop-os/cosmic-comp/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "759bbaea9714fb6c2cdd12688c67df940dd1cf80cb6771e60a7aa96d6f1b69b3",
  },

  "cosmic-edit" = {
    uri = "https://github.com/pop-os/cosmic-edit/archive/refs/tags/epoch-1.0.3.tar.gz",
    sha256sum = "72d490b449360f63e4d64a0729be24e1c7e27bb43c0504901e8b4ddf4ec6ccd2"
  },

  "cosmic-files" = {
    uri = "https://github.com/pop-os/cosmic-files/archive/refs/tags/epoch-1.0.3.tar.gz",
    sha256sum = "7f5343200fd342b82f12df22b801285f4f29ba6a1e6f3770e8070f775998fa37"
  },

  "cosmic-greeter" = {
    uri = "https://github.com/pop-os/cosmic-greeter/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "5dbcbbd0ebd9038f148c66c010b3e9650850a1a99e1ccae2cee49565f3a58c1c",
  },

  "cosmic-icons" = {
    uri = "https://github.com/pop-os/cosmic-icons/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "5687f8f8d268ee754be05b918dcba647480738ed25a3675c5883b47fc6b58f4a",
  },

  "cosmic-idle" = {
    uri = "https://github.com/pop-os/cosmic-idle/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "4c26804a17b8c2bddc9f2b7bba4dcfd00839ef7cbd2a884679f17d57412ce375",
  },

  "cosmic-initial-setup" = {
    uri = "https://github.com/pop-os/cosmic-initial-setup/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "9c78c9075d497d23d0c51d4050c14641ccb97424b78e27d9f0ee7471e1fe4821",
  },

  "cosmic-launcher" = {
    uri = "https://github.com/pop-os/cosmic-launcher/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "6bcda2dac2d9b0d1e5fc0b450718d68d7cc629cc916288813aa5a67e8831db0f",
  },

  "cosmic-notifications" = {
    uri = "https://github.com/pop-os/cosmic-notifications/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "9198b62d9f292367e4c65e695e08c75decccc85b43b3ff9ede934a5310bc6c39",
  },

  "cosmic-osd" = {
    uri = "https://github.com/pop-os/cosmic-osd/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "28dda2197aaa36bf3b52fd856b505114bfcef85dca2cb6194cac5ceaf6373f5c",
  },

  "cosmic-panel" = {
    uri = "https://github.com/pop-os/cosmic-panel/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "fd49d12ce3bc67f0d2dff383a43a20ab48a4d2e0e049dcf9f892781a17909e77",
  },

  "cosmic-randr" = {
    uri = "https://github.com/pop-os/cosmic-randr/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "82196784e611f53f0b5e6ffcdf08d190dcb3a2bf409be1b58713672ff38a706b",
  },

  "cosmic-screenshot" = {
    uri = "https://github.com/pop-os/cosmic-screenshot/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "f59e0aa2604678d2062007ec3b57789b7c49dc906914c4c310aef8ad94d65279",
  },

  "cosmic-session" = {
    uri = "https://github.com/pop-os/cosmic-session/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "7b9f1d00156e4130987365dd0b7953a3612e96c47a59a85ce3f4a2c2801dd992",
  },

  "cosmic-settings-daemon" = {
    uri = "https://github.com/pop-os/cosmic-settings-daemon/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "d8f5e674e2f04e57d42ba004e0e89c97a379d705c1d5815ef12dc074ce907b25",
  },

  "cosmic-settings" = {
    uri = "https://github.com/pop-os/cosmic-settings/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "a0a35ab44d785fe8549978531a85b109289b973532e872f9fee645ceb84f02a0",
  },

  "cosmic-store" = {
    uri = "https://github.com/pop-os/cosmic-store/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "65474c9da7d7507ba19e513be94c31149a4068c27556d7b80b786ea6cbb8f231",
  },

  "cosmic-term" = {
    uri = "https://github.com/pop-os/cosmic-term/archive/refs/tags/epoch-1.0.3.tar.gz",
    sha256sum = "e5f70a1f34669870ee5dbebe97f184e0a3719a9e18320cdaf436c30d357d4724"
  },

  "cosmic-wallpapers" = {
    uri = "https://github.com/pop-os/cosmic-wallpapers/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "cd8abe341356646582e3a55125e103f4709cbbddf0892f2abe8858bc6c7e11de",
  },

  "cosmic-workspaces-epoch" = {
    uri = "https://github.com/pop-os/cosmic-workspaces-epoch/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "ac1581e8e32109ff35df8342ac1fff644b4e9f3a7f6850ee4d6002971d5d8f15",
  },

  "xdg-desktop-portal-cosmic" = {
    uri = "https://github.com/pop-os/xdg-desktop-portal-cosmic/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "b9a4137b0ca6d77c4a737ca65be0d00da4c49326abdd824db2bc560e509cdea6",
  },

  "cosmic-player" = {
    uri = "https://github.com/pop-os/cosmic-player/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "d8034613004b28f6d4eb14c0908253391a454c04f79fe89d1318ba0c9aa9a780",
  },

  "cosmic-player" = {
    uri = "https://github.com/pop-os/cosmic-player/archive/refs/tags/epoch-1.0.5.tar.gz",
    sha256sum = "d8034613004b28f6d4eb14c0908253391a454c04f79fe89d1318ba0c9aa9a780",
  },
}
