{
  "cosmic-applets" = {
    uri = "https://github.com/pop-os/cosmic-applets/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "d04ada3db55f57caa53c6f56f2469862eb5e1c17eb8fee165359fbb7c84b4a74",
  },

  "cosmic-applibrary" = {
    uri = "https://github.com/pop-os/cosmic-applibrary/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "e3b11ac0f37a3004566fbbe2800a1e2c415759fee91833c4a97cb66614e3dba0",
  },

  "cosmic-bg" = {
    uri = "https://github.com/pop-os/cosmic-bg/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "567c7fa2d3a8e35997e1105ecf8a9d2c82b5554031c8676f9b20456e6706e010",
  },

  "cosmic-comp" = {
    uri = "https://github.com/pop-os/cosmic-comp/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "91cee6a89a94cdf02e6af8249ec24e63b275889cf1689d1fb28e653b90de66ab",
  },

  "cosmic-edit" = {
    uri = "https://github.com/pop-os/cosmic-edit/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "c6a3f4d83fb1392328c4090d8462ce9bad640f52754c5df5855d4fe754aae182",
  },

  "cosmic-files" = {
    uri = "https://github.com/pop-os/cosmic-files/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "056db563c21c18fe556f2005b8d4d01993bf370255d491bba7ca6131f0749ac0",
  },

  "cosmic-greeter" = {
    uri = "https://github.com/pop-os/cosmic-greeter/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "7c20566819833b1e93b3f55be9cc0dacf92ab677165aace1f2cde3aa77ed0d3d",
  },

  "cosmic-icons" = {
    uri = "https://github.com/pop-os/cosmic-icons/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "823f34b7041967566cda9ca5cb76d31bff862c18fbcb2b9bcb3f1acaf6258b32",
  },

  "cosmic-idle" = {
    uri = "https://github.com/pop-os/cosmic-idle/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "06203acb3cfe951cfe2f5f3eac4eea7b9bcee9ad37468580c75a6a0e395da49a",
  },

  "cosmic-initial-setup" = {
    uri = "https://github.com/pop-os/cosmic-initial-setup/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "ccc72bd80b8163219221067074d951447dd2ecfbdc23e63ed57b43810f36f33e",
  },

  "cosmic-launcher" = {
    uri = "https://github.com/pop-os/cosmic-launcher/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "cf2d74954ffc523b901ee79c3688cb4db64f4e133dc05bfeb531afdc800fe0ff",
  },

  "cosmic-notifications" = {
    uri = "https://github.com/pop-os/cosmic-notifications/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "0cbdcbe923b7b45313e3d557d2b3b764dd51680251a963871661c6ad582cea20",
  },

  "cosmic-osd" = {
    uri = "https://github.com/pop-os/cosmic-osd/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "d78fbe571bf7f9aa97f33c85278826636bd50b8daa6478312df1454334357409",
  },

  "cosmic-panel" = {
    uri = "https://github.com/pop-os/cosmic-panel/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "99849293c76d2c6d8f3eb4fdaf4f7647ec300fdd5100aaa878cb51e359e171d3",
  },

  "cosmic-randr" = {
    uri = "https://github.com/pop-os/cosmic-randr/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "81e6ce04b4d060fe945a51a52aad47483431e8ef71ecec027c95c587fea0ddd2",
  },

  "cosmic-screenshot" = {
    uri = "https://github.com/pop-os/cosmic-screenshot/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "118b326cace73e505111c16e968919c94f8e2964b8569a2cce416d944873d02e",
  },

  "cosmic-session" = {
    uri = "https://github.com/pop-os/cosmic-session/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "725d133ced95add6fcad02065555d1e5638bbd9c79816f3054651433b8d23024",
  },

  "cosmic-settings-daemon" = {
    uri = "https://github.com/pop-os/cosmic-settings-daemon/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "ea94eb6d5841840f00cb35c8dbc0a3a6e1fe5702f25e7df64936df1ebe49e2ab",
  },

  "cosmic-settings" = {
    uri = "https://github.com/pop-os/cosmic-settings/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "7636bd15f2c62cf094594eab3fa7b8f174f7bb8aba504389b88a86714da9e2b0",
  },

  "cosmic-store" = {
    uri = "https://github.com/pop-os/cosmic-store/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "cd2c251f4cd4ba65ad641e4fc96dd0493dac9ca1a6f314270bda023864f14be9",
  },

  "cosmic-term" = {
    uri = "https://github.com/pop-os/cosmic-term/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "b6d2a5fadb86cac810e308d657faa38b4917cacd5237729f9c019bf70c6d046a",
  },

  "cosmic-wallpapers" = {
    uri = "https://github.com/pop-os/cosmic-wallpapers/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "b16bb3b408fc68e356c365b71b725cc99bb0197dd3596cdf1aca83b039fe0268",
  },

  "cosmic-workspaces-epoch" = {
    uri = "https://github.com/pop-os/cosmic-workspaces-epoch/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "060eac49e96f918638580db119255e47ccf1c9723788e2983d5b310d7aa1c7f7",
  },

  "xdg-desktop-portal-cosmic" = {
    uri = "https://github.com/pop-os/xdg-desktop-portal-cosmic/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "e848f6fdf8910e8a9ab5c182a6ecd0135fab7de69f6c8850a0d5db2d7020aa92",
  },

  "cosmic-player" = {
    uri = "https://github.com/pop-os/cosmic-player/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "c92859c96a0a1180fc2b1fb8944877a18774cb4dbc6365ffefd9d1b35eb78c06",
  },

  "cosmic-player" = {
    uri = "https://github.com/pop-os/cosmic-player/archive/refs/tags/epoch-1.0.6.tar.gz",
    sha256sum = "c92859c96a0a1180fc2b1fb8944877a18774cb4dbc6365ffefd9d1b35eb78c06",
  },
}
