{
  "cosmic-applets" = {
    uri = "https://github.com/pop-os/cosmic-applets/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "69235265de48193f28dd1e62ec4d9160b10a855d7ad86998474b2d4081052415",
  },

  "cosmic-applibrary" = {
    uri = "https://github.com/pop-os/cosmic-applibrary/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "0f942e446aa7fb34b798015814b7eeadda0253659ded50836747edb34e7359ca",
  },

  "cosmic-bg" = {
    uri = "https://github.com/pop-os/cosmic-bg/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "ec69e9724cdc4c5f095b2c6800f845dbd81f7087a816c53d91d01e3169632c81",
  },

  "cosmic-comp" = {
    uri = "https://github.com/pop-os/cosmic-comp/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "4aee50dd9abb4f4a841cc3c4f3f8ebd3c4536bd7f55eefda01395f53fca54593",
  },

  "cosmic-edit" = {
    uri = "https://github.com/pop-os/cosmic-edit/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "5810f6f0f410c55eae2e3cf701fded92e9d3c2b2218dffa0016c7d00d8de6634",
  },

  "cosmic-files" = {
    uri = "https://github.com/pop-os/cosmic-files/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "fc9a053a05973084795d4bade0d869bea20a1e006f0c1740236bfd172c145c7b",
  },

  "cosmic-greeter" = {
    uri = "https://github.com/pop-os/cosmic-greeter/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "8a801c89bf97cbe50953aec43fcdf27e3f80558b34730fd75227854898758295",
  },

  "cosmic-icons" = {
    uri = "https://github.com/pop-os/cosmic-icons/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "38e5927fbdc96f401b076ce4d99e67cc2d1b2010f612b47b56d714bfe050a7bb",
  },

  "cosmic-idle" = {
    uri = "https://github.com/pop-os/cosmic-idle/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "0b93a4daa5eea20ae9a4b007286c5ce69f339cfb83bc46a8a494d04598f83949",
  },

  "cosmic-initial-setup" = {
    uri = "https://github.com/pop-os/cosmic-initial-setup/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "72827c317cf58c7448c366590c1aed5fe4225cd928e8a6a1ee5ee3a5e74c9878",
  },

  "cosmic-launcher" = {
    uri = "https://github.com/pop-os/cosmic-launcher/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "c917ad1700d2004068e74839812b116cd36f89ee02c968dfd9a6940e2e8b448d",
  },

  "cosmic-notifications" = {
    uri = "https://github.com/pop-os/cosmic-notifications/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "ea2bef34f445ba11eaf5eaf674ea9fc0697c5fc3a1568312a0eedfe9a129de4d",
  },

  "cosmic-osd" = {
    uri = "https://github.com/pop-os/cosmic-osd/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "677d584be6039d462ab7d9046e89443b134a8e1b8a1804a8f67bf5c61f8e2125",
  },

  "cosmic-panel" = {
    uri = "https://github.com/pop-os/cosmic-panel/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "665344cfb1bab8972d872d0ff06e66090084d68b8136d239374607448afdce92",
  },

  "cosmic-randr" = {
    uri = "https://github.com/pop-os/cosmic-randr/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "e25c4a165ea48da10b3a31afaa49ff66f020971c1428a9785a807fb27b9bb52d",
  },

  "cosmic-screenshot" = {
    uri = "https://github.com/pop-os/cosmic-screenshot/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "b94d517c34cddb218373ffca80a365b6dde84a28e6d4bf3d7e56df841db45625",
  },

  "cosmic-session" = {
    uri = "https://github.com/pop-os/cosmic-session/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "a9531810b7371adf9e304da36749a8bc3a14cc896bd9ad3ddde8d9907a2ce89d",
  },

  "cosmic-settings-daemon" = {
    uri = "https://github.com/pop-os/cosmic-settings-daemon/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "9e163db9167c3186f7d243ec8dbec46370a86b56b9aacc05b12abef248405a40",
  },

  "cosmic-settings" = {
    uri = "https://github.com/pop-os/cosmic-settings/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "21bebf4658ee63c86f6bb8deb376421ac49b3afdbb0698759bd396ceb6a59c5e",
  },

  "cosmic-store" = {
    uri = "https://github.com/pop-os/cosmic-store/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "9e404b89c46c2e768c7cc9b848cbe7339eacd3738a4d60618403e9a002766e2a",
  },

  "cosmic-term" = {
    uri = "https://github.com/pop-os/cosmic-term/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "35071889a7ab270eb879f2aaaf1ebc1af2d7a6b29c4be54ebb009af3a2207ca1",
  },

  "cosmic-wallpapers" = {
    uri = "https://github.com/pop-os/cosmic-wallpapers/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "a960dfdaa997f0052bd04c52d4694e463af28b28125ec6c783bc48373daeed3f",
  },

  "cosmic-workspaces-epoch" = {
    uri = "https://github.com/pop-os/cosmic-workspaces-epoch/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "bbb04a3c4341229966c9ff68d6e46910f921778b5ba0d86dbd6ec77e752ad22a",
  },

  "xdg-desktop-portal-cosmic" = {
    uri = "https://github.com/pop-os/xdg-desktop-portal-cosmic/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "0008efa59241389ac6bcafb463fd4da43262b8bdfbf0e14379139cea0ba73e1f",
  },

  "cosmic-player" = {
    uri = "https://github.com/pop-os/cosmic-player/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "dbe5546670f0b1ab93d1b8d67cb2c1b8a0a66af035094e4067d0a57223c8f0cb",
  },

  "cosmic-player" = {
    uri = "https://github.com/pop-os/cosmic-player/archive/refs/tags/epoch-1.0.12.tar.gz",
    sha256sum = "dbe5546670f0b1ab93d1b8d67cb2c1b8a0a66af035094e4067d0a57223c8f0cb",
  },
}
