{
  lib,
  drvs,

  slang | lib.AutotoolsPackage
    = {
      singleSource = {
        uri = "https://www.jedsoft.org/releases/slang/slang-2.3.3.tar.bz2",
        sha256sum = "f9145054ae131973c61208ea82486d5dd10e3c5cdad23b7c4a0617743c8f5a18",
      },
      separateBuildDir = false,
      makeTargets = ["static"],
      makeInstallTargets = ["install-static"],

      biDrvs = [
        drvs.ncurses,
      ]
    }
}
