#include <dl_factory.h>

extern void* xkb_compose_state_feed;
extern void* xkb_compose_state_get_compose_table;
extern void* xkb_compose_state_get_one_sym;
extern void* xkb_compose_state_get_status;
extern void* xkb_compose_state_get_utf8;
extern void* xkb_compose_state_new;
extern void* xkb_compose_state_ref;
extern void* xkb_compose_state_reset;
extern void* xkb_compose_state_unref;
extern void* xkb_compose_table_entry_keysym;
extern void* xkb_compose_table_entry_sequence;
extern void* xkb_compose_table_entry_utf8;
extern void* xkb_compose_table_iterator_free;
extern void* xkb_compose_table_iterator_new;
extern void* xkb_compose_table_iterator_next;
extern void* xkb_compose_table_new_from_buffer;
extern void* xkb_compose_table_new_from_file;
extern void* xkb_compose_table_new_from_locale;
extern void* xkb_compose_table_ref;
extern void* xkb_compose_table_unref;
extern void* xkb_file_type_to_string;
extern void* xkb_components_from_rmlvo_builder;
extern void* xkb_components_from_rules_names;
extern void* xkb_components_names_from_rules;
extern void* xkb_context_get_log_level;
extern void* xkb_context_get_log_verbosity;
extern void* xkb_context_get_user_data;
extern void* xkb_context_include_path_append;
extern void* xkb_context_include_path_append_default;
extern void* xkb_context_include_path_clear;
extern void* xkb_context_include_path_get;
extern void* xkb_context_include_path_get_extra_path;
extern void* xkb_context_include_path_get_system_path;
extern void* xkb_context_include_path_get_unversioned_extensions_path;
extern void* xkb_context_include_path_get_versioned_extensions_path;
extern void* xkb_context_include_path_reset_defaults;
extern void* xkb_context_new;
extern void* xkb_context_num_include_paths;
extern void* xkb_context_ref;
extern void* xkb_context_set_log_fn;
extern void* xkb_context_set_log_level;
extern void* xkb_context_set_log_verbosity;
extern void* xkb_context_set_user_data;
extern void* xkb_context_unref;
extern void* xkb_atom_intern;
extern void* xkb_atom_lookup;
extern void* xkb_atom_table_size;
extern void* xkb_atom_text;
extern void* xkb_context_failed_include_path_get;
extern void* xkb_context_get_buffer;
extern void* xkb_context_getenv;
extern void* xkb_context_init_includes;
extern void* xkb_context_num_failed_include_paths;
extern void* xkb_context_sanitize_rule_names;
extern void* xkb_log;
extern void* xkb_keysym_from_name;
extern void* xkb_keysym_get_explicit_names;
extern void* xkb_keysym_get_name;
extern void* xkb_keysym_is_assigned;
extern void* xkb_keysym_is_deprecated;
extern void* xkb_keysym_is_keypad;
extern void* xkb_keysym_is_modifier;
extern void* xkb_keysym_iterator_get_keysym;
extern void* xkb_keysym_iterator_get_name;
extern void* xkb_keysym_iterator_is_explicitly_named;
extern void* xkb_keysym_iterator_new;
extern void* xkb_keysym_iterator_next;
extern void* xkb_keysym_iterator_unref;
extern void* xkb_keysym_is_lower;
extern void* xkb_keysym_is_upper_or_title;
extern void* xkb_keysym_to_lower;
extern void* xkb_keysym_to_upper;
extern void* xkb_keysym_to_utf32;
extern void* xkb_keysym_to_utf8;
extern void* xkb_utf32_to_keysym;
extern void* xkb_keymap_get_as_string;
extern void* xkb_keymap_get_as_string2;
extern void* xkb_keymap_key_by_name;
extern void* xkb_keymap_key_for_each;
extern void* xkb_keymap_key_get_level;
extern void* xkb_keymap_key_get_mods_for_level;
extern void* xkb_keymap_key_get_name;
extern void* xkb_keymap_key_get_syms_by_level;
extern void* xkb_keymap_key_repeats;
extern void* xkb_keymap_layout_get_index;
extern void* xkb_keymap_layout_get_name;
extern void* xkb_keymap_led_get_index;
extern void* xkb_keymap_led_get_name;
extern void* xkb_keymap_max_keycode;
extern void* xkb_keymap_min_keycode;
extern void* xkb_keymap_mod_get_index;
extern void* xkb_keymap_mod_get_mask;
extern void* xkb_keymap_mod_get_mask2;
extern void* xkb_keymap_mod_get_name;
extern void* xkb_keymap_new_from_buffer;
extern void* xkb_keymap_new_from_file;
extern void* xkb_keymap_new_from_names;
extern void* xkb_keymap_new_from_names2;
extern void* xkb_keymap_new_from_rmlvo;
extern void* xkb_keymap_new_from_string;
extern void* xkb_keymap_num_layouts;
extern void* xkb_keymap_num_layouts_for_key;
extern void* xkb_keymap_num_leds;
extern void* xkb_keymap_num_levels_for_key;
extern void* xkb_keymap_num_mods;
extern void* xkb_keymap_ref;
extern void* xkb_keymap_unref;
extern void* xkb_keymap_compare;
extern void* xkb_keymap_key_get_actions_by_level;
extern void* xkb_keymap_new;
extern void* xkb_rmlvo_builder_append_layout;
extern void* xkb_rmlvo_builder_append_option;
extern void* xkb_rmlvo_builder_new;
extern void* xkb_rmlvo_builder_ref;
extern void* xkb_rmlvo_builder_to_rules_names;
extern void* xkb_rmlvo_builder_unref;
extern void* xkb_state_get_keymap;
extern void* xkb_state_key_get_consumed_mods;
extern void* xkb_state_key_get_consumed_mods2;
extern void* xkb_state_key_get_layout;
extern void* xkb_state_key_get_level;
extern void* xkb_state_key_get_one_sym;
extern void* xkb_state_key_get_syms;
extern void* xkb_state_key_get_utf32;
extern void* xkb_state_key_get_utf8;
extern void* xkb_state_layout_index_is_active;
extern void* xkb_state_layout_name_is_active;
extern void* xkb_state_led_index_is_active;
extern void* xkb_state_led_name_is_active;
extern void* xkb_state_mod_index_is_active;
extern void* xkb_state_mod_index_is_consumed;
extern void* xkb_state_mod_index_is_consumed2;
extern void* xkb_state_mod_indices_are_active;
extern void* xkb_state_mod_mask_remove_consumed;
extern void* xkb_state_mod_name_is_active;
extern void* xkb_state_mod_names_are_active;
extern void* xkb_state_new;
extern void* xkb_state_ref;
extern void* xkb_state_serialize_layout;
extern void* xkb_state_serialize_mods;
extern void* xkb_state_unref;
extern void* xkb_state_update_key;
extern void* xkb_state_update_latched_locked;
extern void* xkb_state_update_mask;

__attribute__((constructor)) static void register_libxkbcommon_so_0(){
    register_lib("libxkbcommon.so.0", 144);
    // register_lib("libxkbcommon.so", 0);
    register_symbol("xkb_compose_state_feed", &xkb_compose_state_feed);
	register_symbol("xkb_compose_state_get_compose_table", &xkb_compose_state_get_compose_table);
	register_symbol("xkb_compose_state_get_one_sym", &xkb_compose_state_get_one_sym);
	register_symbol("xkb_compose_state_get_status", &xkb_compose_state_get_status);
	register_symbol("xkb_compose_state_get_utf8", &xkb_compose_state_get_utf8);
	register_symbol("xkb_compose_state_new", &xkb_compose_state_new);
	register_symbol("xkb_compose_state_ref", &xkb_compose_state_ref);
	register_symbol("xkb_compose_state_reset", &xkb_compose_state_reset);
	register_symbol("xkb_compose_state_unref", &xkb_compose_state_unref);
	register_symbol("xkb_compose_table_entry_keysym", &xkb_compose_table_entry_keysym);
	register_symbol("xkb_compose_table_entry_sequence", &xkb_compose_table_entry_sequence);
	register_symbol("xkb_compose_table_entry_utf8", &xkb_compose_table_entry_utf8);
	register_symbol("xkb_compose_table_iterator_free", &xkb_compose_table_iterator_free);
	register_symbol("xkb_compose_table_iterator_new", &xkb_compose_table_iterator_new);
	register_symbol("xkb_compose_table_iterator_next", &xkb_compose_table_iterator_next);
	register_symbol("xkb_compose_table_new_from_buffer", &xkb_compose_table_new_from_buffer);
	register_symbol("xkb_compose_table_new_from_file", &xkb_compose_table_new_from_file);
	register_symbol("xkb_compose_table_new_from_locale", &xkb_compose_table_new_from_locale);
	register_symbol("xkb_compose_table_ref", &xkb_compose_table_ref);
	register_symbol("xkb_compose_table_unref", &xkb_compose_table_unref);
	register_symbol("xkb_file_type_to_string", &xkb_file_type_to_string);
	register_symbol("xkb_components_from_rmlvo_builder", &xkb_components_from_rmlvo_builder);
	register_symbol("xkb_components_from_rules_names", &xkb_components_from_rules_names);
	register_symbol("xkb_components_names_from_rules", &xkb_components_names_from_rules);
	register_symbol("xkb_context_get_log_level", &xkb_context_get_log_level);
	register_symbol("xkb_context_get_log_verbosity", &xkb_context_get_log_verbosity);
	register_symbol("xkb_context_get_user_data", &xkb_context_get_user_data);
	register_symbol("xkb_context_include_path_append", &xkb_context_include_path_append);
	register_symbol("xkb_context_include_path_append_default", &xkb_context_include_path_append_default);
	register_symbol("xkb_context_include_path_clear", &xkb_context_include_path_clear);
	register_symbol("xkb_context_include_path_get", &xkb_context_include_path_get);
	register_symbol("xkb_context_include_path_get_extra_path", &xkb_context_include_path_get_extra_path);
	register_symbol("xkb_context_include_path_get_system_path", &xkb_context_include_path_get_system_path);
	register_symbol("xkb_context_include_path_get_unversioned_extensions_path", &xkb_context_include_path_get_unversioned_extensions_path);
	register_symbol("xkb_context_include_path_get_versioned_extensions_path", &xkb_context_include_path_get_versioned_extensions_path);
	register_symbol("xkb_context_include_path_reset_defaults", &xkb_context_include_path_reset_defaults);
	register_symbol("xkb_context_new", &xkb_context_new);
	register_symbol("xkb_context_num_include_paths", &xkb_context_num_include_paths);
	register_symbol("xkb_context_ref", &xkb_context_ref);
	register_symbol("xkb_context_set_log_fn", &xkb_context_set_log_fn);
	register_symbol("xkb_context_set_log_level", &xkb_context_set_log_level);
	register_symbol("xkb_context_set_log_verbosity", &xkb_context_set_log_verbosity);
	register_symbol("xkb_context_set_user_data", &xkb_context_set_user_data);
	register_symbol("xkb_context_unref", &xkb_context_unref);
	register_symbol("xkb_atom_intern", &xkb_atom_intern);
	register_symbol("xkb_atom_lookup", &xkb_atom_lookup);
	register_symbol("xkb_atom_table_size", &xkb_atom_table_size);
	register_symbol("xkb_atom_text", &xkb_atom_text);
	register_symbol("xkb_context_failed_include_path_get", &xkb_context_failed_include_path_get);
	register_symbol("xkb_context_get_buffer", &xkb_context_get_buffer);
	register_symbol("xkb_context_getenv", &xkb_context_getenv);
	register_symbol("xkb_context_init_includes", &xkb_context_init_includes);
	register_symbol("xkb_context_num_failed_include_paths", &xkb_context_num_failed_include_paths);
	register_symbol("xkb_context_sanitize_rule_names", &xkb_context_sanitize_rule_names);
	register_symbol("xkb_log", &xkb_log);
	register_symbol("xkb_keysym_from_name", &xkb_keysym_from_name);
	register_symbol("xkb_keysym_get_explicit_names", &xkb_keysym_get_explicit_names);
	register_symbol("xkb_keysym_get_name", &xkb_keysym_get_name);
	register_symbol("xkb_keysym_is_assigned", &xkb_keysym_is_assigned);
	register_symbol("xkb_keysym_is_deprecated", &xkb_keysym_is_deprecated);
	register_symbol("xkb_keysym_is_keypad", &xkb_keysym_is_keypad);
	register_symbol("xkb_keysym_is_modifier", &xkb_keysym_is_modifier);
	register_symbol("xkb_keysym_iterator_get_keysym", &xkb_keysym_iterator_get_keysym);
	register_symbol("xkb_keysym_iterator_get_name", &xkb_keysym_iterator_get_name);
	register_symbol("xkb_keysym_iterator_is_explicitly_named", &xkb_keysym_iterator_is_explicitly_named);
	register_symbol("xkb_keysym_iterator_new", &xkb_keysym_iterator_new);
	register_symbol("xkb_keysym_iterator_next", &xkb_keysym_iterator_next);
	register_symbol("xkb_keysym_iterator_unref", &xkb_keysym_iterator_unref);
	register_symbol("xkb_keysym_is_lower", &xkb_keysym_is_lower);
	register_symbol("xkb_keysym_is_upper_or_title", &xkb_keysym_is_upper_or_title);
	register_symbol("xkb_keysym_to_lower", &xkb_keysym_to_lower);
	register_symbol("xkb_keysym_to_upper", &xkb_keysym_to_upper);
	register_symbol("xkb_keysym_to_utf32", &xkb_keysym_to_utf32);
	register_symbol("xkb_keysym_to_utf8", &xkb_keysym_to_utf8);
	register_symbol("xkb_utf32_to_keysym", &xkb_utf32_to_keysym);
	register_symbol("xkb_keymap_get_as_string", &xkb_keymap_get_as_string);
	register_symbol("xkb_keymap_get_as_string2", &xkb_keymap_get_as_string2);
	register_symbol("xkb_keymap_key_by_name", &xkb_keymap_key_by_name);
	register_symbol("xkb_keymap_key_for_each", &xkb_keymap_key_for_each);
	register_symbol("xkb_keymap_key_get_level", &xkb_keymap_key_get_level);
	register_symbol("xkb_keymap_key_get_mods_for_level", &xkb_keymap_key_get_mods_for_level);
	register_symbol("xkb_keymap_key_get_name", &xkb_keymap_key_get_name);
	register_symbol("xkb_keymap_key_get_syms_by_level", &xkb_keymap_key_get_syms_by_level);
	register_symbol("xkb_keymap_key_repeats", &xkb_keymap_key_repeats);
	register_symbol("xkb_keymap_layout_get_index", &xkb_keymap_layout_get_index);
	register_symbol("xkb_keymap_layout_get_name", &xkb_keymap_layout_get_name);
	register_symbol("xkb_keymap_led_get_index", &xkb_keymap_led_get_index);
	register_symbol("xkb_keymap_led_get_name", &xkb_keymap_led_get_name);
	register_symbol("xkb_keymap_max_keycode", &xkb_keymap_max_keycode);
	register_symbol("xkb_keymap_min_keycode", &xkb_keymap_min_keycode);
	register_symbol("xkb_keymap_mod_get_index", &xkb_keymap_mod_get_index);
	register_symbol("xkb_keymap_mod_get_mask", &xkb_keymap_mod_get_mask);
	register_symbol("xkb_keymap_mod_get_mask2", &xkb_keymap_mod_get_mask2);
	register_symbol("xkb_keymap_mod_get_name", &xkb_keymap_mod_get_name);
	register_symbol("xkb_keymap_new_from_buffer", &xkb_keymap_new_from_buffer);
	register_symbol("xkb_keymap_new_from_file", &xkb_keymap_new_from_file);
	register_symbol("xkb_keymap_new_from_names", &xkb_keymap_new_from_names);
	register_symbol("xkb_keymap_new_from_names2", &xkb_keymap_new_from_names2);
	register_symbol("xkb_keymap_new_from_rmlvo", &xkb_keymap_new_from_rmlvo);
	register_symbol("xkb_keymap_new_from_string", &xkb_keymap_new_from_string);
	register_symbol("xkb_keymap_num_layouts", &xkb_keymap_num_layouts);
	register_symbol("xkb_keymap_num_layouts_for_key", &xkb_keymap_num_layouts_for_key);
	register_symbol("xkb_keymap_num_leds", &xkb_keymap_num_leds);
	register_symbol("xkb_keymap_num_levels_for_key", &xkb_keymap_num_levels_for_key);
	register_symbol("xkb_keymap_num_mods", &xkb_keymap_num_mods);
	register_symbol("xkb_keymap_ref", &xkb_keymap_ref);
	register_symbol("xkb_keymap_unref", &xkb_keymap_unref);
	register_symbol("xkb_keymap_compare", &xkb_keymap_compare);
	register_symbol("xkb_keymap_key_get_actions_by_level", &xkb_keymap_key_get_actions_by_level);
	register_symbol("xkb_keymap_new", &xkb_keymap_new);
	register_symbol("xkb_rmlvo_builder_append_layout", &xkb_rmlvo_builder_append_layout);
	register_symbol("xkb_rmlvo_builder_append_option", &xkb_rmlvo_builder_append_option);
	register_symbol("xkb_rmlvo_builder_new", &xkb_rmlvo_builder_new);
	register_symbol("xkb_rmlvo_builder_ref", &xkb_rmlvo_builder_ref);
	register_symbol("xkb_rmlvo_builder_to_rules_names", &xkb_rmlvo_builder_to_rules_names);
	register_symbol("xkb_rmlvo_builder_unref", &xkb_rmlvo_builder_unref);
	register_symbol("xkb_state_get_keymap", &xkb_state_get_keymap);
	register_symbol("xkb_state_key_get_consumed_mods", &xkb_state_key_get_consumed_mods);
	register_symbol("xkb_state_key_get_consumed_mods2", &xkb_state_key_get_consumed_mods2);
	register_symbol("xkb_state_key_get_layout", &xkb_state_key_get_layout);
	register_symbol("xkb_state_key_get_level", &xkb_state_key_get_level);
	register_symbol("xkb_state_key_get_one_sym", &xkb_state_key_get_one_sym);
	register_symbol("xkb_state_key_get_syms", &xkb_state_key_get_syms);
	register_symbol("xkb_state_key_get_utf32", &xkb_state_key_get_utf32);
	register_symbol("xkb_state_key_get_utf8", &xkb_state_key_get_utf8);
	register_symbol("xkb_state_layout_index_is_active", &xkb_state_layout_index_is_active);
	register_symbol("xkb_state_layout_name_is_active", &xkb_state_layout_name_is_active);
	register_symbol("xkb_state_led_index_is_active", &xkb_state_led_index_is_active);
	register_symbol("xkb_state_led_name_is_active", &xkb_state_led_name_is_active);
	register_symbol("xkb_state_mod_index_is_active", &xkb_state_mod_index_is_active);
	register_symbol("xkb_state_mod_index_is_consumed", &xkb_state_mod_index_is_consumed);
	register_symbol("xkb_state_mod_index_is_consumed2", &xkb_state_mod_index_is_consumed2);
	register_symbol("xkb_state_mod_indices_are_active", &xkb_state_mod_indices_are_active);
	register_symbol("xkb_state_mod_mask_remove_consumed", &xkb_state_mod_mask_remove_consumed);
	register_symbol("xkb_state_mod_name_is_active", &xkb_state_mod_name_is_active);
	register_symbol("xkb_state_mod_names_are_active", &xkb_state_mod_names_are_active);
	register_symbol("xkb_state_new", &xkb_state_new);
	register_symbol("xkb_state_ref", &xkb_state_ref);
	register_symbol("xkb_state_serialize_layout", &xkb_state_serialize_layout);
	register_symbol("xkb_state_serialize_mods", &xkb_state_serialize_mods);
	register_symbol("xkb_state_unref", &xkb_state_unref);
	register_symbol("xkb_state_update_key", &xkb_state_update_key);
	register_symbol("xkb_state_update_latched_locked", &xkb_state_update_latched_locked);
	register_symbol("xkb_state_update_mask", &xkb_state_update_mask);
}

extern void* eglBindAPI;
extern void* eglBindTexImage;
extern void* eglBindWaylandDisplayWL;
extern void* eglChooseConfig;
extern void* eglClientWaitSync;
extern void* eglClientWaitSyncKHR;
extern void* eglCopyBuffers;
extern void* eglCreateContext;
extern void* eglCreateImage;
extern void* eglCreateImageKHR;
extern void* eglCreatePbufferFromClientBuffer;
extern void* eglCreatePbufferSurface;
extern void* eglCreatePixmapSurface;
extern void* eglCreatePlatformPixmapSurface;
extern void* eglCreatePlatformPixmapSurfaceEXT;
extern void* eglCreatePlatformWindowSurface;
extern void* eglCreatePlatformWindowSurfaceEXT;
extern void* eglCreateSync;
extern void* eglCreateSync64KHR;
extern void* eglCreateSyncKHR;
extern void* eglCreateWaylandBufferFromImageWL;
extern void* eglCreateWindowSurface;
extern void* eglDebugMessageControlKHR;
extern void* eglDestroyContext;
extern void* eglDestroyImage;
extern void* eglDestroyImageKHR;
extern void* eglDestroySurface;
extern void* eglDestroySync;
extern void* eglDestroySyncKHR;
extern void* eglDupNativeFenceFDANDROID;
extern void* eglExportDMABUFImageMESA;
extern void* eglExportDMABUFImageQueryMESA;
extern void* eglGetConfigAttrib;
extern void* eglGetConfigs;
extern void* eglGetCurrentContext;
extern void* eglGetCurrentDisplay;
extern void* eglGetCurrentSurface;
extern void* eglGetDisplay;
extern void* eglGetDisplayDriverConfig;
extern void* eglGetDisplayDriverName;
extern void* eglGetError;
extern void* eglGetMscRateANGLE;
extern void* eglGetPlatformDisplay;
extern void* eglGetPlatformDisplayEXT;
extern void* eglGetProcAddress;
extern void* eglGetSyncAttrib;
extern void* eglGetSyncAttribKHR;
extern void* eglGetSyncValuesCHROMIUM;
extern void* eglInitialize;
extern void* eglLabelObjectKHR;
extern void* eglMakeCurrent;
extern void* eglQueryAPI;
extern void* eglQueryContext;
extern void* eglQueryDebugKHR;
extern void* eglQueryDeviceAttribEXT;
extern void* eglQueryDeviceBinaryEXT;
extern void* eglQueryDeviceStringEXT;
extern void* eglQueryDevicesEXT;
extern void* eglQueryDisplayAttribEXT;
extern void* eglQueryDmaBufFormatsEXT;
extern void* eglQueryDmaBufModifiersEXT;
extern void* eglQueryString;
extern void* eglQuerySupportedCompressionRatesEXT;
extern void* eglQuerySurface;
extern void* eglQueryWaylandBufferWL;
extern void* eglReleaseTexImage;
extern void* eglReleaseThread;
extern void* eglSetBlobCacheFuncsANDROID;
extern void* eglSetDamageRegionKHR;
extern void* eglSignalSyncKHR;
extern void* eglSurfaceAttrib;
extern void* eglSwapBuffers;
extern void* eglSwapBuffersWithDamageEXT;
extern void* eglSwapBuffersWithDamageKHR;
extern void* eglSwapInterval;
extern void* eglTerminate;
extern void* eglUnbindWaylandDisplayWL;
extern void* eglWaitClient;
extern void* eglWaitGL;
extern void* eglWaitNative;
extern void* eglWaitSync;
extern void* eglWaitSyncKHR;
extern void* eglPrintConfigDebug;


__attribute__((constructor)) void register_libEGL_so_1(){
	register_lib("libEGL.so.1", 83);

	register_symbol("eglBindAPI", &eglBindAPI);
	register_symbol("eglBindTexImage", &eglBindTexImage);
	register_symbol("eglBindWaylandDisplayWL", &eglBindWaylandDisplayWL);
	register_symbol("eglChooseConfig", &eglChooseConfig);
	register_symbol("eglClientWaitSync", &eglClientWaitSync);
	register_symbol("eglClientWaitSyncKHR", &eglClientWaitSyncKHR);
	register_symbol("eglCopyBuffers", &eglCopyBuffers);
	register_symbol("eglCreateContext", &eglCreateContext);
	register_symbol("eglCreateImage", &eglCreateImage);
	register_symbol("eglCreateImageKHR", &eglCreateImageKHR);
	register_symbol("eglCreatePbufferFromClientBuffer", &eglCreatePbufferFromClientBuffer);
	register_symbol("eglCreatePbufferSurface", &eglCreatePbufferSurface);
	register_symbol("eglCreatePixmapSurface", &eglCreatePixmapSurface);
	register_symbol("eglCreatePlatformPixmapSurface", &eglCreatePlatformPixmapSurface);
	register_symbol("eglCreatePlatformPixmapSurfaceEXT", &eglCreatePlatformPixmapSurfaceEXT);
	register_symbol("eglCreatePlatformWindowSurface", &eglCreatePlatformWindowSurface);
	register_symbol("eglCreatePlatformWindowSurfaceEXT", &eglCreatePlatformWindowSurfaceEXT);
	register_symbol("eglCreateSync", &eglCreateSync);
	register_symbol("eglCreateSync64KHR", &eglCreateSync64KHR);
	register_symbol("eglCreateSyncKHR", &eglCreateSyncKHR);
	register_symbol("eglCreateWaylandBufferFromImageWL", &eglCreateWaylandBufferFromImageWL);
	register_symbol("eglCreateWindowSurface", &eglCreateWindowSurface);
	register_symbol("eglDebugMessageControlKHR", &eglDebugMessageControlKHR);
	register_symbol("eglDestroyContext", &eglDestroyContext);
	register_symbol("eglDestroyImage", &eglDestroyImage);
	register_symbol("eglDestroyImageKHR", &eglDestroyImageKHR);
	register_symbol("eglDestroySurface", &eglDestroySurface);
	register_symbol("eglDestroySync", &eglDestroySync);
	register_symbol("eglDestroySyncKHR", &eglDestroySyncKHR);
	register_symbol("eglDupNativeFenceFDANDROID", &eglDupNativeFenceFDANDROID);
	register_symbol("eglExportDMABUFImageMESA", &eglExportDMABUFImageMESA);
	register_symbol("eglExportDMABUFImageQueryMESA", &eglExportDMABUFImageQueryMESA);
	register_symbol("eglGetConfigAttrib", &eglGetConfigAttrib);
	register_symbol("eglGetConfigs", &eglGetConfigs);
	register_symbol("eglGetCurrentContext", &eglGetCurrentContext);
	register_symbol("eglGetCurrentDisplay", &eglGetCurrentDisplay);
	register_symbol("eglGetCurrentSurface", &eglGetCurrentSurface);
	register_symbol("eglGetDisplay", &eglGetDisplay);
	register_symbol("eglGetDisplayDriverConfig", &eglGetDisplayDriverConfig);
	register_symbol("eglGetDisplayDriverName", &eglGetDisplayDriverName);
	register_symbol("eglGetError", &eglGetError);
	register_symbol("eglGetMscRateANGLE", &eglGetMscRateANGLE);
	register_symbol("eglGetPlatformDisplay", &eglGetPlatformDisplay);
	register_symbol("eglGetPlatformDisplayEXT", &eglGetPlatformDisplayEXT);
	register_symbol("eglGetProcAddress", &eglGetProcAddress);
	register_symbol("eglGetSyncAttrib", &eglGetSyncAttrib);
	register_symbol("eglGetSyncAttribKHR", &eglGetSyncAttribKHR);
	register_symbol("eglGetSyncValuesCHROMIUM", &eglGetSyncValuesCHROMIUM);
	register_symbol("eglInitialize", &eglInitialize);
	register_symbol("eglLabelObjectKHR", &eglLabelObjectKHR);
	register_symbol("eglMakeCurrent", &eglMakeCurrent);
	register_symbol("eglQueryAPI", &eglQueryAPI);
	register_symbol("eglQueryContext", &eglQueryContext);
	register_symbol("eglQueryDebugKHR", &eglQueryDebugKHR);
	register_symbol("eglQueryDeviceAttribEXT", &eglQueryDeviceAttribEXT);
	register_symbol("eglQueryDeviceBinaryEXT", &eglQueryDeviceBinaryEXT);
	register_symbol("eglQueryDeviceStringEXT", &eglQueryDeviceStringEXT);
	register_symbol("eglQueryDevicesEXT", &eglQueryDevicesEXT);
	register_symbol("eglQueryDisplayAttribEXT", &eglQueryDisplayAttribEXT);
	register_symbol("eglQueryDmaBufFormatsEXT", &eglQueryDmaBufFormatsEXT);
	register_symbol("eglQueryDmaBufModifiersEXT", &eglQueryDmaBufModifiersEXT);
	register_symbol("eglQueryString", &eglQueryString);
	register_symbol("eglQuerySupportedCompressionRatesEXT", &eglQuerySupportedCompressionRatesEXT);
	register_symbol("eglQuerySurface", &eglQuerySurface);
	register_symbol("eglQueryWaylandBufferWL", &eglQueryWaylandBufferWL);
	register_symbol("eglReleaseTexImage", &eglReleaseTexImage);
	register_symbol("eglReleaseThread", &eglReleaseThread);
	register_symbol("eglSetBlobCacheFuncsANDROID", &eglSetBlobCacheFuncsANDROID);
	register_symbol("eglSetDamageRegionKHR", &eglSetDamageRegionKHR);
	register_symbol("eglSignalSyncKHR", &eglSignalSyncKHR);
	register_symbol("eglSurfaceAttrib", &eglSurfaceAttrib);
	register_symbol("eglSwapBuffers", &eglSwapBuffers);
	register_symbol("eglSwapBuffersWithDamageEXT", &eglSwapBuffersWithDamageEXT);
	register_symbol("eglSwapBuffersWithDamageKHR", &eglSwapBuffersWithDamageKHR);
	register_symbol("eglSwapInterval", &eglSwapInterval);
	register_symbol("eglTerminate", &eglTerminate);
	register_symbol("eglUnbindWaylandDisplayWL", &eglUnbindWaylandDisplayWL);
	register_symbol("eglWaitClient", &eglWaitClient);
	register_symbol("eglWaitGL", &eglWaitGL);
	register_symbol("eglWaitNative", &eglWaitNative);
	register_symbol("eglWaitSync", &eglWaitSync);
	register_symbol("eglWaitSyncKHR", &eglWaitSyncKHR);
	register_symbol("eglPrintConfigDebug", &eglPrintConfigDebug);

};

