#!/bin/sh
rm -rf /tmp/ssh
mkdir -p /tmp/ssh
chmod 600 /tmp/ssh
touch /tmp/ssh/unsecure-file
scp \
	-o StrictHostKeyChecking=no -o UserKnownHostsFile=/tmp/ssh/known_host \
	-i /tmp/ssh/unsecure-file \
	$@
