
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>

#define DLSYM(sym, prefix) 	\
    if (strcmp(symbol, #sym) == 0) { \
        extern void* prefix##sym; \
		dbg_print("(dlsym) found symbol %s with handle=%p, address=%p\n", symbol, handle, &prefix##sym); \
        return &prefix##sym; \
    }

static char* dbg;
static char dbg_initualilised = 0;

static void dbg_initilialise(){
	dbg = getenv("DL_DEBUG");
	dbg_initualilised = 1;
}
static void dbg_print(const char *s, ...)
{
	if (dbg_initualilised==0){
		dbg_initilialise();
	}

    if (dbg != NULL)
    {
        va_list args;
        va_start(args, s);
        vfprintf(stderr, s, args);
    }
}

//  Should be safe to do nothing (https://github.com/mozilla/nss/blob/86e9cefa456dece91add2ccb257b319d4929cedb/lib/freebl/loader.c#L859)
void BL_Unload(void){

}

extern void *stub_dlopen(const char *, int);
extern void *stub_dlsym(void *__restrict, const char *__restrict);
extern int stub_dladdr(const void *handle, Dl_info *info);

const char* main_program_handle = "main_program";

const char* lib_libpci_so_3_libpci_so = "lib_libpci_so_3_libpci_so";
const char* lib_libEGL_so_1 = "lib_libEGL_so_1";
const char* lib_libsoftokn3_so = "lib_libsoftokn3_so";
const char* lib_libfreeblpriv3_so = "lib_libfreeblpriv3_so";

void* dlopen(const char *path, int mode) {
	if (path == NULL) { return &main_program_handle; }
	if (strcmp( path, "libpci.so.3" ) == 0) { dbg_print("(dlopen) found library libpci.so.3 (handle=%p)\n", &lib_libpci_so_3_libpci_so); return &lib_libpci_so_3_libpci_so; }
	if (strcmp( path, "libpci.so" ) == 0) { dbg_print("(dlopen) found library libpci.so (handle=%p)\n", &lib_libpci_so_3_libpci_so); return &lib_libpci_so_3_libpci_so; }
	if (strcmp( path, "libEGL.so.1" ) == 0) { dbg_print("(dlopen) found library libEGL.so.1 (handle=%p)\n", &lib_libEGL_so_1); return &lib_libEGL_so_1; }
	if (strcmp( path, "libsoftokn3.so" ) == 0) { dbg_print("(dlopen) found library libsoftokn3.so (handle=%p)\n", &lib_libsoftokn3_so); return &lib_libsoftokn3_so; }
	if (strcmp( path, "libfreeblpriv3.so" ) == 0) { dbg_print("(dlopen) found library libfreeblpriv3.so (handle=%p)\n", &lib_libfreeblpriv3_so); return &lib_libfreeblpriv3_so; }
	fprintf(stderr, "(dlopen) WARNING: failed for path %s\n", path);	return stub_dlopen(path, mode);
}

void* dlsym(void *__restrict handle, const char *__restrict symbol) {
	if (handle == &lib_libpci_so_3_libpci_so || handle == NULL || handle == &main_program_handle) { 
		DLSYM(pci_alloc, )
		DLSYM(pci_alloc_dev, )
		DLSYM(pci_cleanup, )
		DLSYM(pci_clone_access, )
		DLSYM(pci_define_param, )
		DLSYM(pci_fill_info, )
		DLSYM(pci_fill_info_v313, )
		DLSYM(pci_filter_init, )
		DLSYM(pci_filter_init_v30, )
		DLSYM(pci_filter_init_v38, )
		DLSYM(pci_filter_match, )
		DLSYM(pci_filter_match_v30, )
		DLSYM(pci_filter_match_v38, )
		DLSYM(pci_filter_parse_id, )
		DLSYM(pci_filter_parse_id_v30, )
		DLSYM(pci_filter_parse_id_v38, )
		DLSYM(pci_filter_parse_slot, )
		DLSYM(pci_filter_parse_slot_v30, )
		DLSYM(pci_filter_parse_slot_v38, )
		DLSYM(pci_find_cap, )
		DLSYM(pci_find_cap_nr, )
		DLSYM(pci_free_caps, )
		DLSYM(pci_free_dev, )
		DLSYM(pci_free_name_list, )
		DLSYM(pci_free_params, )
		DLSYM(pci_generic_block_read, )
		DLSYM(pci_generic_block_write, )
		DLSYM(pci_generic_fill_info, )
		DLSYM(pci_generic_scan, )
		DLSYM(pci_generic_scan_bus, )
		DLSYM(pci_generic_scan_domain, )
		DLSYM(pci_get_dev, )
		DLSYM(pci_get_method_name, )
		DLSYM(pci_get_param, )
		DLSYM(pci_get_string_property, )
		DLSYM(pci_id_cache_dirty, )
		DLSYM(pci_id_cache_flush, )
		DLSYM(pci_id_cache_load, )
		DLSYM(pci_id_hash_free, )
		DLSYM(pci_id_hwdb_free, )
		DLSYM(pci_id_hwdb_lookup, )
		DLSYM(pci_id_insert, )
		DLSYM(pci_id_lookup, )
		DLSYM(pci_id_net_lookup, )
		DLSYM(pci_init, )
		DLSYM(pci_init_internal, )
		DLSYM(pci_init_v35, )
		DLSYM(pci_link_dev, )
		DLSYM(pci_load_name_list, )
		DLSYM(pci_lookup_method, )
		DLSYM(pci_lookup_name, )
		DLSYM(pci_malloc, )
		DLSYM(pci_mfree, )
		DLSYM(pci_read_block, )
		DLSYM(pci_read_byte, )
		DLSYM(pci_read_long, )
		DLSYM(pci_read_vpd, )
		DLSYM(pci_read_word, )
		DLSYM(pci_scan_bus, )
		DLSYM(pci_scan_caps, )
		DLSYM(pci_set_name_list_path, )
		DLSYM(pci_set_param, )
		DLSYM(pci_set_param_internal, )
		DLSYM(pci_set_property, )
		DLSYM(pci_setup_cache, )
		DLSYM(pci_strdup, )
		DLSYM(pci_walk_params, )
		DLSYM(pci_write_block, )
		DLSYM(pci_write_byte, )
		DLSYM(pci_write_long, )
		DLSYM(pci_write_word, )
		DLSYM(physmem_access, )
		DLSYM(physmem_close, )
		DLSYM(physmem_get_pagesize, )
		DLSYM(physmem_init_config, )
		DLSYM(physmem_map, )
		DLSYM(physmem_open, )
		DLSYM(physmem_unmap, )
		DLSYM(pm_dump, )
		DLSYM(pm_ecam, )
		DLSYM(pm_intel_conf1, )
		DLSYM(pm_intel_conf2, )
		DLSYM(pm_linux_proc, )
		DLSYM(pm_linux_sysfs, )
		DLSYM(pm_mmio_conf1, )
		DLSYM(pm_mmio_conf1_ext, )
	}
	if (handle == &lib_libEGL_so_1 || handle == NULL || handle == &main_program_handle) { 
		DLSYM(eglBindAPI, )
		DLSYM(eglBindTexImage, )
		DLSYM(eglChooseConfig, )
		DLSYM(eglClientWaitSync, )
		DLSYM(eglCopyBuffers, )
		DLSYM(eglCreateContext, )
		DLSYM(eglCreateImage, )
		DLSYM(eglCreatePbufferFromClientBuffer, )
		DLSYM(eglCreatePbufferSurface, )
		DLSYM(eglCreatePixmapSurface, )
		DLSYM(eglCreatePlatformPixmapSurface, )
		DLSYM(eglCreatePlatformWindowSurface, )
		DLSYM(eglCreateSync, )
		DLSYM(eglCreateWindowSurface, )
		DLSYM(eglDestroyContext, )
		DLSYM(eglDestroyImage, )
		DLSYM(eglDestroySurface, )
		DLSYM(eglDestroySync, )
		DLSYM(eglGetConfigAttrib, )
		DLSYM(eglGetConfigs, )
		DLSYM(eglGetCurrentContext, )
		DLSYM(eglGetCurrentDisplay, )
		DLSYM(eglGetCurrentSurface, )
		DLSYM(eglGetDisplay, )
		DLSYM(eglGetError, )
		DLSYM(eglGetPlatformDisplay, )
		DLSYM(eglGetProcAddress, )
		DLSYM(eglGetSyncAttrib, )
		DLSYM(eglInitialize, )
		DLSYM(eglMakeCurrent, )
		DLSYM(eglPrintConfigDebug, )
		DLSYM(eglQueryAPI, )
		DLSYM(eglQueryContext, )
		DLSYM(eglQueryString, )
		DLSYM(eglQuerySurface, )
		DLSYM(eglReleaseTexImage, )
		DLSYM(eglReleaseThread, )
		DLSYM(eglSurfaceAttrib, )
		DLSYM(eglSwapBuffers, )
		DLSYM(eglSwapInterval, )
		DLSYM(eglTerminate, )
		DLSYM(eglWaitClient, )
		DLSYM(eglWaitGL, )
		DLSYM(eglWaitNative, )
		DLSYM(eglWaitSync, )
	}
	if (handle == &lib_libsoftokn3_so || handle == NULL || handle == &main_program_handle) { 
		DLSYM(FC_AsyncComplete, )
		DLSYM(FC_AsyncGetID, )
		DLSYM(FC_AsyncJoin, )
		DLSYM(FC_CancelFunction, )
		DLSYM(FC_CloseAllSessions, )
		DLSYM(FC_CloseSession, )
		DLSYM(FC_CopyObject, )
		DLSYM(FC_CreateObject, )
		DLSYM(FC_DecapsulateKey, )
		DLSYM(FC_Decrypt, )
		DLSYM(FC_DecryptDigestUpdate, )
		DLSYM(FC_DecryptFinal, )
		DLSYM(FC_DecryptInit, )
		DLSYM(FC_DecryptMessage, )
		DLSYM(FC_DecryptMessageBegin, )
		DLSYM(FC_DecryptMessageNext, )
		DLSYM(FC_DecryptUpdate, )
		DLSYM(FC_DecryptVerifyUpdate, )
		DLSYM(FC_DeriveKey, )
		DLSYM(FC_DestroyObject, )
		DLSYM(FC_Digest, )
		DLSYM(FC_DigestEncryptUpdate, )
		DLSYM(FC_DigestFinal, )
		DLSYM(FC_DigestInit, )
		DLSYM(FC_DigestKey, )
		DLSYM(FC_DigestUpdate, )
		DLSYM(FC_EncapsulateKey, )
		DLSYM(FC_Encrypt, )
		DLSYM(FC_EncryptFinal, )
		DLSYM(FC_EncryptInit, )
		DLSYM(FC_EncryptMessage, )
		DLSYM(FC_EncryptMessageBegin, )
		DLSYM(FC_EncryptMessageNext, )
		DLSYM(FC_EncryptUpdate, )
		DLSYM(FC_Finalize, )
		DLSYM(FC_FindObjects, )
		DLSYM(FC_FindObjectsFinal, )
		DLSYM(FC_FindObjectsInit, )
		DLSYM(FC_GenerateKey, )
		DLSYM(FC_GenerateKeyPair, )
		DLSYM(FC_GenerateRandom, )
		DLSYM(fc_getAttribute, )
		DLSYM(FC_GetAttributeValue, )
		DLSYM(FC_GetFunctionList, )
		DLSYM(FC_GetFunctionStatus, )
		DLSYM(FC_GetInfo, )
		DLSYM(FC_GetInfoV2, )
		DLSYM(FC_GetInterface, )
		DLSYM(FC_GetInterfaceList, )
		DLSYM(FC_GetMechanismInfo, )
		DLSYM(FC_GetMechanismInfoV2, )
		DLSYM(FC_GetMechanismList, )
		DLSYM(FC_GetObjectSize, )
		DLSYM(FC_GetOperationState, )
		DLSYM(FC_GetSessionInfo, )
		DLSYM(FC_GetSessionValidationFlags, )
		DLSYM(FC_GetSlotInfo, )
		DLSYM(FC_GetSlotList, )
		DLSYM(FC_GetTokenInfo, )
		DLSYM(FC_Initialize, )
		DLSYM(FC_InitPIN, )
		DLSYM(FC_InitToken, )
		DLSYM(FC_Login, )
		DLSYM(fc_log_init_error, )
		DLSYM(FC_LoginUser, )
		DLSYM(FC_Logout, )
		DLSYM(FC_MessageDecryptFinal, )
		DLSYM(FC_MessageDecryptInit, )
		DLSYM(FC_MessageEncryptFinal, )
		DLSYM(FC_MessageEncryptInit, )
		DLSYM(FC_MessageSignFinal, )
		DLSYM(FC_MessageSignInit, )
		DLSYM(FC_MessageVerifyFinal, )
		DLSYM(FC_MessageVerifyInit, )
		DLSYM(FC_OpenSession, )
		DLSYM(FC_SeedRandom, )
		DLSYM(FC_SessionCancel, )
		DLSYM(FC_SetAttributeValue, )
		DLSYM(FC_SetOperationState, )
		DLSYM(FC_SetPIN, )
		DLSYM(FC_Sign, )
		DLSYM(FC_SignEncryptUpdate, )
		DLSYM(FC_SignFinal, )
		DLSYM(FC_SignInit, )
		DLSYM(FC_SignMessage, )
		DLSYM(FC_SignMessageBegin, )
		DLSYM(FC_SignMessageNext, )
		DLSYM(FC_SignRecover, )
		DLSYM(FC_SignRecoverInit, )
		DLSYM(FC_SignUpdate, )
		DLSYM(FC_UnwrapKey, )
		DLSYM(FC_UnwrapKeyAuthenticated, )
		DLSYM(FC_Verify, )
		DLSYM(FC_VerifyFinal, )
		DLSYM(FC_VerifyInit, )
		DLSYM(FC_VerifyMessage, )
		DLSYM(FC_VerifyMessageBegin, )
		DLSYM(FC_VerifyMessageNext, )
		DLSYM(FC_VerifyRecover, )
		DLSYM(FC_VerifyRecoverInit, )
		DLSYM(FC_VerifySignature, )
		DLSYM(FC_VerifySignatureFinal, )
		DLSYM(FC_VerifySignatureInit, )
		DLSYM(FC_VerifySignatureUpdate, )
		DLSYM(FC_VerifyUpdate, )
		DLSYM(FC_WaitForSlotEvent, )
		DLSYM(FC_WrapKey, )
		DLSYM(FC_WrapKeyAuthenticated, )
		DLSYM(NSC_AsyncComplete, )
		DLSYM(NSC_AsyncGetID, )
		DLSYM(NSC_AsyncJoin, )
		DLSYM(NSC_CancelFunction, )
		DLSYM(NSC_CloseAllSessions, )
		DLSYM(NSC_CloseSession, )
		DLSYM(nsc_CommonFinalize, )
		DLSYM(nsc_CommonGetSlotList, )
		DLSYM(nsc_CommonInitialize, )
		DLSYM(NSC_CopyObject, )
		DLSYM(NSC_CreateObject, )
		DLSYM(NSC_Decapsulate, )
		DLSYM(NSC_DecapsulateKey, )
		DLSYM(NSC_Decrypt, )
		DLSYM(NSC_DecryptDigestUpdate, )
		DLSYM(NSC_DecryptFinal, )
		DLSYM(NSC_DecryptInit, )
		DLSYM(NSC_DecryptMessage, )
		DLSYM(NSC_DecryptMessageBegin, )
		DLSYM(NSC_DecryptMessageNext, )
		DLSYM(NSC_DecryptUpdate, )
		DLSYM(NSC_DecryptVerifyUpdate, )
		DLSYM(NSC_DeriveKey, )
		DLSYM(NSC_DestroyObject, )
		DLSYM(NSC_Digest, )
		DLSYM(NSC_DigestEncryptUpdate, )
		DLSYM(NSC_DigestFinal, )
		DLSYM(NSC_DigestInit, )
		DLSYM(NSC_DigestKey, )
		DLSYM(NSC_DigestUpdate, )
		DLSYM(NSC_Encapsulate, )
		DLSYM(NSC_EncapsulateKey, )
		DLSYM(NSC_Encrypt, )
		DLSYM(NSC_EncryptFinal, )
		DLSYM(NSC_EncryptInit, )
		DLSYM(NSC_EncryptMessage, )
		DLSYM(NSC_EncryptMessageBegin, )
		DLSYM(NSC_EncryptMessageNext, )
		DLSYM(NSC_EncryptUpdate, )
		DLSYM(NSC_Finalize, )
		DLSYM(NSC_FindObjects, )
		DLSYM(NSC_FindObjectsFinal, )
		DLSYM(NSC_FindObjectsInit, )
		DLSYM(NSC_GenerateKey, )
		DLSYM(NSC_GenerateKeyPair, )
		DLSYM(NSC_GenerateRandom, )
		DLSYM(NSC_GetAttributeValue, )
		DLSYM(NSC_GetFunctionList, )
		DLSYM(NSC_GetFunctionStatus, )
		DLSYM(NSC_GetInfo, )
		DLSYM(NSC_GetInfoV2, )
		DLSYM(NSC_GetInterface, )
		DLSYM(NSC_GetInterfaceList, )
		DLSYM(NSC_GetMechanismInfo, )
		DLSYM(NSC_GetMechanismInfoV2, )
		DLSYM(NSC_GetMechanismList, )
		DLSYM(NSC_GetObjectSize, )
		DLSYM(NSC_GetOperationState, )
		DLSYM(NSC_GetSessionInfo, )
		DLSYM(NSC_GetSessionValidationFlags, )
		DLSYM(NSC_GetSlotInfo, )
		DLSYM(NSC_GetSlotList, )
		DLSYM(NSC_GetTokenInfo, )
		DLSYM(NSC_Initialize, )
		DLSYM(NSC_InitPIN, )
		DLSYM(NSC_InitToken, )
		DLSYM(NSC_Login, )
		DLSYM(NSC_LoginUser, )
		DLSYM(NSC_Logout, )
		DLSYM(NSC_MessageDecryptFinal, )
		DLSYM(NSC_MessageDecryptInit, )
		DLSYM(NSC_MessageEncryptFinal, )
		DLSYM(NSC_MessageEncryptInit, )
		DLSYM(NSC_MessageSignFinal, )
		DLSYM(NSC_MessageSignInit, )
		DLSYM(NSC_MessageVerifyFinal, )
		DLSYM(NSC_MessageVerifyInit, )
		DLSYM(NSC_ModuleDBFunc, )
		DLSYM(NSC_OpenSession, )
		DLSYM(NSC_SeedRandom, )
		DLSYM(NSC_SessionCancel, )
		DLSYM(NSC_SetAttributeValue, )
		DLSYM(NSC_SetOperationState, )
		DLSYM(NSC_SetPIN, )
		DLSYM(nsc_SetupHMACKeyGen, )
		DLSYM(NSC_Sign, )
		DLSYM(NSC_SignEncryptUpdate, )
		DLSYM(NSC_SignFinal, )
		DLSYM(NSC_SignInit, )
		DLSYM(NSC_SignMessage, )
		DLSYM(NSC_SignMessageBegin, )
		DLSYM(NSC_SignMessageNext, )
		DLSYM(NSC_SignRecover, )
		DLSYM(NSC_SignRecoverInit, )
		DLSYM(NSC_SignUpdate, )
		DLSYM(NSC_UnwrapKey, )
		DLSYM(NSC_UnwrapKeyAuthenticated, )
		DLSYM(NSC_Verify, )
		DLSYM(NSC_VerifyFinal, )
		DLSYM(NSC_VerifyInit, )
		DLSYM(NSC_VerifyMessage, )
		DLSYM(NSC_VerifyMessageBegin, )
		DLSYM(NSC_VerifyMessageNext, )
		DLSYM(NSC_VerifyRecover, )
		DLSYM(NSC_VerifyRecoverInit, )
		DLSYM(NSC_VerifySignature, )
		DLSYM(NSC_VerifySignatureFinal, )
		DLSYM(NSC_VerifySignatureInit, )
		DLSYM(NSC_VerifySignatureUpdate, )
		DLSYM(NSC_VerifyUpdate, )
		DLSYM(NSC_WaitForSlotEvent, )
		DLSYM(NSC_WrapKey, )
		DLSYM(NSC_WrapKeyAuthenticated, )
		DLSYM(sdb_Abort, )
		DLSYM(sdb_Begin, )
		DLSYM(sdb_Close, )
		DLSYM(sdb_Commit, )
		DLSYM(sdb_CreateObject, )
		DLSYM(sdb_destroyAnyObject, )
		DLSYM(sdb_DestroyMetaData, )
		DLSYM(sdb_DestroyObject, )
		DLSYM(sdb_FindObjects, )
		DLSYM(sdb_FindObjectsFinal, )
		DLSYM(sdb_FindObjectsInit, )
		DLSYM(sdb_GetAttributeValue, )
		DLSYM(sdb_GetMetaData, )
		DLSYM(sdb_GetNewObjectID, )
		DLSYM(sdb_init, )
		DLSYM(sdb_PutMetaData, )
		DLSYM(sdb_Reset, )
		DLSYM(sdb_SetAttributeValue, )
		DLSYM(sdb_SetForkState, )
		DLSYM(sftk_AddAttributeType, )
		DLSYM(sftk_addHandle, )
		DLSYM(sftk_AddObject, )
		DLSYM(sftk_AddSlotObject, )
		DLSYM(sftk_AES_DestroyContext, )
		DLSYM(sftk_aes_xcbc_new_keys, )
		DLSYM(sftk_Attribute2SecItem, )
		DLSYM(sftk_Attribute2SSecItem, )
		DLSYM(sftk_AttributeToFlags, )
		DLSYM(sftk_AuditCopyObject, )
		DLSYM(sftk_AuditCreateObject, )
		DLSYM(sftk_AuditCryptInit, )
		DLSYM(sftk_AuditDecapsulateKey, )
		DLSYM(sftk_AuditDeriveKey, )
		DLSYM(sftk_AuditDestroyObject, )
		DLSYM(sftk_AuditDigestKey, )
		DLSYM(sftk_AuditEncapsulateKey, )
		DLSYM(sftk_AuditGenerateKey, )
		DLSYM(sftk_AuditGenerateKeyPair, )
		DLSYM(sftk_AuditGetAttributeValue, )
		DLSYM(sftk_AuditGetObjectSize, )
		DLSYM(sftk_AuditSetAttributeValue, )
		DLSYM(sftk_AuditUnwrapKey, )
		DLSYM(sftk_AuditWrapKey, )
		DLSYM(sftk_ChaCha20Poly1305_DestroyContext, )
		DLSYM(sftk_CheckCBCPadding, )
		DLSYM(sftk_CheckDESKey, )
		DLSYM(sftk_CKRVToMask, )
		DLSYM(sftk_CleanupFreeLists, )
		DLSYM(sftk_ClearSession, )
		DLSYM(SFTK_ClearTokenKeyHashTable, )
		DLSYM(sftk_CloseAllSessions, )
		DLSYM(sftk_compareKeysEqual, )
		DLSYM(sftk_ConstrainAttribute, )
		DLSYM(sftk_convertSessionToToken, )
		DLSYM(sftk_CopyObject, )
		DLSYM(sftk_CopyTokenObject, )
		DLSYM(sftk_CreateValidationObjects, )
		DLSYM(sftk_CryptInit, )
		DLSYM(sftkdb_Abort, )
		DLSYM(sftkdb_Begin, )
		DLSYM(sftkdb_ChangePassword, )
		DLSYM(sftkdb_CheckPassword, )
		DLSYM(sftkdb_CheckPasswordNull, )
		DLSYM(sftkdb_ClearPassword, )
		DLSYM(sftkdb_CloseDB, )
		DLSYM(sftkdb_Commit, )
		DLSYM(sftkdb_convertObjects, )
		DLSYM(sftkdb_DecryptAttribute, )
		DLSYM(sftkdb_DestroyAttributeSignature, )
		DLSYM(sftkdb_DestroyObject, )
		DLSYM(sftkdb_dropAttribute, )
		DLSYM(sftkdb_dropTrustAttribute, )
		DLSYM(sftkdb_EncryptAttribute, )
		DLSYM(sftkdb_FindObjects, )
		DLSYM(sftkdb_FindObjectsFinal, )
		DLSYM(sftkdb_FindObjectsInit, )
		DLSYM(sftkdb_finishPasswordCheck, )
		DLSYM(sftkdb_FreeUpdatePasswordKey, )
		DLSYM(sftkdb_GetAttributeSignature, )
		DLSYM(sftkdb_GetAttributeValue, )
		DLSYM(sftkdb_GetUpdateID, )
		DLSYM(sftkdb_GetUpdatePasswordKey, )
		DLSYM(sftkdb_HasPasswordSet, )
		DLSYM(sftk_DBInit, )
		DLSYM(sftkdb_InUpdateMerge, )
		DLSYM(sftkdb_isNullTrust, )
		DLSYM(sftkdb_isULONGAttribute, )
		DLSYM(sftkdb_mapNSSTrustAttributeTypeToTrustAttributeType, )
		DLSYM(sftkdb_mapNSSTrustToPKCS11Trust, )
		DLSYM(sftkdb_mapNSSTrustValueToPKCS11TrustValue, )
		DLSYM(sftkdb_mapTrustAttribute, )
		DLSYM(sftkdb_NeedUpdateDBPassword, )
		DLSYM(sftkdb_PutAttributeSignature, )
		DLSYM(sftkdb_PWCached, )
		DLSYM(sftkdb_reconcileTrustEntry, )
		DLSYM(sftkdb_ResetKeyDB, )
		DLSYM(sftkdb_SetAttributeValue, )
		DLSYM(sftkdb_Shutdown, )
		DLSYM(sftkdb_SignAttribute, )
		DLSYM(sftkdb_TypeString, )
		DLSYM(sftkdb_Update, )
		DLSYM(sftkdb_VerifyAttribute, )
		DLSYM(sftkdb_write, )
		DLSYM(sftk_defaultAttribute, )
		DLSYM(sftk_DeleteAttributeType, )
		DLSYM(sftk_DeleteObject, )
		DLSYM(sftk_DeriveEncrypt, )
		DLSYM(SFTK_DestroySlotData, )
		DLSYM(sftk_emailhack, )
		DLSYM(sftk_EncodeInteger, )
		DLSYM(sftk_ExtractTemplate, )
		DLSYM(sftk_FindAttribute, )
		DLSYM(sftk_FIPSEntryOK, )
		DLSYM(sftk_fips_IKE_PowerUpSelfTests, )
		DLSYM(sftk_fips_pbkdf_PowerUpSelfTests, )
		DLSYM(sftk_fips_SP800_108_PowerUpSelfTests, )
		DLSYM(sftk_forceAttribute, )
		DLSYM(sftk_ForkReset, )
		DLSYM(sftk_FormatDESKey, )
		DLSYM(sftk_FreeAttribute, )
		DLSYM(sftk_FreeContext, )
		DLSYM(sftk_freeDB, )
		DLSYM(SFTKFree_nsslowkey_DestroyPrivateKey, )
		DLSYM(SFTKFree_nsslowkey_DestroyPublicKey, )
		DLSYM(sftk_FreeObject, )
		DLSYM(sftk_FreeObjectList, )
		DLSYM(sftk_FreeObjectListElement, )
		DLSYM(sftk_freeParams, )
		DLSYM(sftk_FreeSearch, )
		DLSYM(sftk_FreeSession, )
		DLSYM(sftk_getCertDB, )
		DLSYM(sftk_GetContext, )
		DLSYM(sftk_getDBForTokenObject, )
		DLSYM(sftk_getDefSlotName, )
		DLSYM(sftk_getDefTokName, )
		DLSYM(sftk_GetHashTypeFromMechanism, )
		DLSYM(sftk_getKeyDB, )
		DLSYM(sftk_GetLengthInBits, )
		DLSYM(sftk_getNextHandle, )
		DLSYM(sftk_GetObjectFromList, )
		DLSYM(sftk_GetPrivKey, )
		DLSYM(sftk_GetPubKey, )
		DLSYM(sftk_GetULongAttribute, )
		DLSYM(sftk_handleObject, )
		DLSYM(sftk_hasAttribute, )
		DLSYM(sftk_hasAttributeToken, )
		DLSYM(sftk_hasFIPS, )
		DLSYM(sftk_HKDF, )
		DLSYM(sftk_HMACConstantTime_New, )
		DLSYM(sftk_HMACConstantTime_Update, )
		DLSYM(sftk_HMACMechanismToHash, )
		DLSYM(sftk_ike1_appendix_b_prf, )
		DLSYM(sftk_ike1_prf, )
		DLSYM(sftk_ike_prf, )
		DLSYM(sftk_ike_prf_plus, )
		DLSYM(sftk_InitFreeLists, )
		DLSYM(sftk_InitGeneric, )
		DLSYM(sftk_InitSession, )
		DLSYM(sftk_InstallContext, )
		DLSYM(sftk_isLegacyIterationCountAllowed, )
		DLSYM(sftk_IsSafePrime, )
		DLSYM(sftk_isSensitive, )
		DLSYM(sftk_isTrue, )
		DLSYM(sftk_IsWeakKey, )
		DLSYM(sftk_kyber_AllocCiphertextItem, )
		DLSYM(sftk_kyber_AllocPrivKeyItem, )
		DLSYM(sftk_kyber_AllocPubKeyItem, )
		DLSYM(sftk_kyber_InternalToPK11Param, )
		DLSYM(sftk_kyber_PK11ParamToInternal, )
		DLSYM(sftk_kyber_pubKeyLen, )
		DLSYM(sftk_LogAuditMessage, )
		DLSYM(sftk_MACConstantTime_DestroyContext, )
		DLSYM(sftk_MACConstantTime_EndHash, )
		DLSYM(sftk_MAC_Create, )
		DLSYM(sftk_MAC_DestroyContext, )
		DLSYM(sftk_MAC_End, )
		DLSYM(sftk_MAC_Init, )
		DLSYM(sftk_MAC_InitRaw, )
		DLSYM(sftk_MAC_Reset, )
		DLSYM(sftk_MAC_Update, )
		DLSYM(sftk_MapCryptError, )
		DLSYM(sftk_MapDecryptError, )
		DLSYM(sftk_MapKeySize, )
		DLSYM(sftk_mapLinuxAuditType, )
		DLSYM(sftk_MapVerifyError, )
		DLSYM(sftk_MechAllowsOperation, )
		DLSYM(sftk_MLDSAGetSigLen, )
		DLSYM(sftk_MLDSASignFinal, )
		DLSYM(sftk_MLDSASignUpdate, )
		DLSYM(sftk_MLDSAVerifyFinal, )
		DLSYM(sftk_MLDSAVerifyUpdate, )
		DLSYM(sftk_modifyType, )
		DLSYM(sftk_MultipleAttribute2SecItem, )
		DLSYM(sftk_narrowToSessionObject, )
		DLSYM(sftk_narrowToTokenObject, )
		DLSYM(sftk_NewObject, )
		DLSYM(sftk_NewSession, )
		DLSYM(sftk_NewTokenObject, )
		DLSYM(sftk_NullHashEnd, )
		DLSYM(sftk_ObjectFromHandle, )
		DLSYM(sftk_objectMatch, )
		DLSYM(sftk_operationIsFIPS, )
		DLSYM(sftk_parseParameters, )
		DLSYM(sftk_PBELockInit, )
		DLSYM(sftk_PBELockShutdown, )
		DLSYM(sftk_PutPubKey, )
		DLSYM(sftk_RawArgHasFlag, )
		DLSYM(sftk_ReadAttribute, )
		DLSYM(sftk_ReferenceObject, )
		DLSYM(sftk_ReturnContextByType, )
		DLSYM(sftk_searchObjectList, )
		DLSYM(sftk_SessionFromHandle, )
		DLSYM(sftk_SetContextByType, )
		DLSYM(sftk_setFIPS, )
		DLSYM(SFTK_ShutdownSlot, )
		DLSYM(sftk_SlotFromID, )
		DLSYM(sftk_SlotFromSessionHandle, )
		DLSYM(sftk_SlotIDFromSessionHandle, )
		DLSYM(SFTK_SlotInit, )
		DLSYM(SFTK_SlotReInit, )
		DLSYM(sftk_SSLv3MACConstantTime_New, )
		DLSYM(sftk_SSLv3MACConstantTime_Update, )
		DLSYM(sftk_template_hasAttribute, )
		DLSYM(sftk_TerminateOp, )
		DLSYM(sftk_TLSPRFInit, )
		DLSYM(sftk_ULong2SDBULong, )
		DLSYM(sftk_UninstallContext, )
		DLSYM(sftk_update_all_states, )
		DLSYM(sftk_update_state, )
		DLSYM(sftk_VerifyDH_Prime, )
		DLSYM(sftk_xcbc_mac_pad, )
		DLSYM(s_open, )
		DLSYM(s_shutdown, )
		DLSYM(stfk_CopyTokenAttributes, )
		DLSYM(stfk_CopyTokenPrivateKey, )
		DLSYM(stfk_CopyTokenPublicKey, )
		DLSYM(stfk_CopyTokenSecretKey, )
	}
	if (handle == &lib_libfreeblpriv3_so || handle == NULL || handle == &main_program_handle) { 
		DLSYM(FREEBL_Deprecated, )
		DLSYM(FREEBL_GetVector, )
	}

	DLSYM(localtime, )
    DLSYM(localtime_r, )
    DLSYM(getaddrinfo, )

	fprintf(stderr, "(dlsym) WARNING: failed for symbol %s (handle=%p)\n", symbol, handle);	return stub_dlsym(handle, symbol);
}


int dladdr(const void *handle, Dl_info *info)
{
    fprintf(stderr, "(dladdr) handle=\"%p\"\n", handle);
    return stub_dladdr(handle, info);
}

