
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>

extern void *stub_dlopen(const char *, int);
extern void *stub_dlsym(void *__restrict, const char *__restrict);
extern int stub_dladdr(const void *handle, Dl_info *info);

const char* main_program_handle = "main_program";

const char* lib_libEGL_so_1 = "lib_libEGL_so_1";
const char* lib_libGLESv2_so_2 = "lib_libGLESv2_so_2";

void* dlopen(const char *path, int mode) {
	if (path == NULL) { return &main_program_handle; }
	if (strcmp( path, "libEGL.so.1" ) == 0) { return &lib_libEGL_so_1; }
	if (strcmp( path, "libGLESv2.so.2" ) == 0) { return &lib_libGLESv2_so_2; }
	fprintf(stderr, "(dlopen) WARNING: failed for path %s\n", path);	return stub_dlopen(path, mode);
}

void* dlsym(void *__restrict handle, const char *__restrict symbol) {
	if (handle == &lib_libEGL_so_1 || handle == NULL || handle == &main_program_handle) { 
		if (strcmp(symbol, "eglBindAPI") == 0) { extern void* eglBindAPI; return &eglBindAPI; }
		if (strcmp(symbol, "eglBindTexImage") == 0) { extern void* eglBindTexImage; return &eglBindTexImage; }
		if (strcmp(symbol, "eglChooseConfig") == 0) { extern void* eglChooseConfig; return &eglChooseConfig; }
		if (strcmp(symbol, "eglClientWaitSync") == 0) { extern void* eglClientWaitSync; return &eglClientWaitSync; }
		if (strcmp(symbol, "eglCopyBuffers") == 0) { extern void* eglCopyBuffers; return &eglCopyBuffers; }
		if (strcmp(symbol, "eglCreateContext") == 0) { extern void* eglCreateContext; return &eglCreateContext; }
		if (strcmp(symbol, "eglCreateImage") == 0) { extern void* eglCreateImage; return &eglCreateImage; }
		if (strcmp(symbol, "eglCreatePbufferFromClientBuffer") == 0) { extern void* eglCreatePbufferFromClientBuffer; return &eglCreatePbufferFromClientBuffer; }
		if (strcmp(symbol, "eglCreatePbufferSurface") == 0) { extern void* eglCreatePbufferSurface; return &eglCreatePbufferSurface; }
		if (strcmp(symbol, "eglCreatePixmapSurface") == 0) { extern void* eglCreatePixmapSurface; return &eglCreatePixmapSurface; }
		if (strcmp(symbol, "eglCreatePlatformPixmapSurface") == 0) { extern void* eglCreatePlatformPixmapSurface; return &eglCreatePlatformPixmapSurface; }
		if (strcmp(symbol, "eglCreatePlatformWindowSurface") == 0) { extern void* eglCreatePlatformWindowSurface; return &eglCreatePlatformWindowSurface; }
		if (strcmp(symbol, "eglCreateSync") == 0) { extern void* eglCreateSync; return &eglCreateSync; }
		if (strcmp(symbol, "eglCreateWindowSurface") == 0) { extern void* eglCreateWindowSurface; return &eglCreateWindowSurface; }
		if (strcmp(symbol, "eglDestroyContext") == 0) { extern void* eglDestroyContext; return &eglDestroyContext; }
		if (strcmp(symbol, "eglDestroyImage") == 0) { extern void* eglDestroyImage; return &eglDestroyImage; }
		if (strcmp(symbol, "eglDestroySurface") == 0) { extern void* eglDestroySurface; return &eglDestroySurface; }
		if (strcmp(symbol, "eglDestroySync") == 0) { extern void* eglDestroySync; return &eglDestroySync; }
		if (strcmp(symbol, "eglGetConfigAttrib") == 0) { extern void* eglGetConfigAttrib; return &eglGetConfigAttrib; }
		if (strcmp(symbol, "eglGetConfigs") == 0) { extern void* eglGetConfigs; return &eglGetConfigs; }
		if (strcmp(symbol, "eglGetCurrentContext") == 0) { extern void* eglGetCurrentContext; return &eglGetCurrentContext; }
		if (strcmp(symbol, "eglGetCurrentDisplay") == 0) { extern void* eglGetCurrentDisplay; return &eglGetCurrentDisplay; }
		if (strcmp(symbol, "eglGetCurrentSurface") == 0) { extern void* eglGetCurrentSurface; return &eglGetCurrentSurface; }
		if (strcmp(symbol, "eglGetDisplay") == 0) { extern void* eglGetDisplay; return &eglGetDisplay; }
		if (strcmp(symbol, "eglGetError") == 0) { extern void* eglGetError; return &eglGetError; }
		if (strcmp(symbol, "eglGetPlatformDisplay") == 0) { extern void* eglGetPlatformDisplay; return &eglGetPlatformDisplay; }
		if (strcmp(symbol, "eglGetProcAddress") == 0) { extern void* eglGetProcAddress; return &eglGetProcAddress; }
		if (strcmp(symbol, "eglGetSyncAttrib") == 0) { extern void* eglGetSyncAttrib; return &eglGetSyncAttrib; }
		if (strcmp(symbol, "eglInitialize") == 0) { extern void* eglInitialize; return &eglInitialize; }
		if (strcmp(symbol, "eglMakeCurrent") == 0) { extern void* eglMakeCurrent; return &eglMakeCurrent; }
		if (strcmp(symbol, "eglQueryAPI") == 0) { extern void* eglQueryAPI; return &eglQueryAPI; }
		if (strcmp(symbol, "eglQueryContext") == 0) { extern void* eglQueryContext; return &eglQueryContext; }
		if (strcmp(symbol, "eglQueryString") == 0) { extern void* eglQueryString; return &eglQueryString; }
		if (strcmp(symbol, "eglQuerySurface") == 0) { extern void* eglQuerySurface; return &eglQuerySurface; }
		if (strcmp(symbol, "eglReleaseTexImage") == 0) { extern void* eglReleaseTexImage; return &eglReleaseTexImage; }
		if (strcmp(symbol, "eglReleaseThread") == 0) { extern void* eglReleaseThread; return &eglReleaseThread; }
		if (strcmp(symbol, "eglSurfaceAttrib") == 0) { extern void* eglSurfaceAttrib; return &eglSurfaceAttrib; }
		if (strcmp(symbol, "eglSwapBuffers") == 0) { extern void* eglSwapBuffers; return &eglSwapBuffers; }
		if (strcmp(symbol, "eglSwapInterval") == 0) { extern void* eglSwapInterval; return &eglSwapInterval; }
		if (strcmp(symbol, "eglTerminate") == 0) { extern void* eglTerminate; return &eglTerminate; }
		if (strcmp(symbol, "eglWaitClient") == 0) { extern void* eglWaitClient; return &eglWaitClient; }
		if (strcmp(symbol, "eglWaitGL") == 0) { extern void* eglWaitGL; return &eglWaitGL; }
		if (strcmp(symbol, "eglWaitNative") == 0) { extern void* eglWaitNative; return &eglWaitNative; }
		if (strcmp(symbol, "eglWaitSync") == 0) { extern void* eglWaitSync; return &eglWaitSync; }
		if (strcmp(symbol, "eglPrintConfigDebug") == 0) { extern void* eglPrintConfigDebug; return &eglPrintConfigDebug; }
	}
	if (handle == &lib_libGLESv2_so_2 || handle == NULL || handle == &main_program_handle) { 
		if (strcmp(symbol, "glActiveShaderProgram") == 0) { extern void* glActiveShaderProgram; return &glActiveShaderProgram; }
		if (strcmp(symbol, "glActiveTexture") == 0) { extern void* glActiveTexture; return &glActiveTexture; }
		if (strcmp(symbol, "glAttachShader") == 0) { extern void* glAttachShader; return &glAttachShader; }
		if (strcmp(symbol, "glBeginQuery") == 0) { extern void* glBeginQuery; return &glBeginQuery; }
		if (strcmp(symbol, "glBeginTransformFeedback") == 0) { extern void* glBeginTransformFeedback; return &glBeginTransformFeedback; }
		if (strcmp(symbol, "glBindAttribLocation") == 0) { extern void* glBindAttribLocation; return &glBindAttribLocation; }
		if (strcmp(symbol, "glBindBuffer") == 0) { extern void* glBindBuffer; return &glBindBuffer; }
		if (strcmp(symbol, "glBindBufferBase") == 0) { extern void* glBindBufferBase; return &glBindBufferBase; }
		if (strcmp(symbol, "glBindBufferRange") == 0) { extern void* glBindBufferRange; return &glBindBufferRange; }
		if (strcmp(symbol, "glBindFramebuffer") == 0) { extern void* glBindFramebuffer; return &glBindFramebuffer; }
		if (strcmp(symbol, "glBindImageTexture") == 0) { extern void* glBindImageTexture; return &glBindImageTexture; }
		if (strcmp(symbol, "glBindProgramPipeline") == 0) { extern void* glBindProgramPipeline; return &glBindProgramPipeline; }
		if (strcmp(symbol, "glBindRenderbuffer") == 0) { extern void* glBindRenderbuffer; return &glBindRenderbuffer; }
		if (strcmp(symbol, "glBindSampler") == 0) { extern void* glBindSampler; return &glBindSampler; }
		if (strcmp(symbol, "glBindTexture") == 0) { extern void* glBindTexture; return &glBindTexture; }
		if (strcmp(symbol, "glBindTransformFeedback") == 0) { extern void* glBindTransformFeedback; return &glBindTransformFeedback; }
		if (strcmp(symbol, "glBindVertexArray") == 0) { extern void* glBindVertexArray; return &glBindVertexArray; }
		if (strcmp(symbol, "glBindVertexBuffer") == 0) { extern void* glBindVertexBuffer; return &glBindVertexBuffer; }
		if (strcmp(symbol, "glBlendBarrier") == 0) { extern void* glBlendBarrier; return &glBlendBarrier; }
		if (strcmp(symbol, "glBlendColor") == 0) { extern void* glBlendColor; return &glBlendColor; }
		if (strcmp(symbol, "glBlendEquation") == 0) { extern void* glBlendEquation; return &glBlendEquation; }
		if (strcmp(symbol, "glBlendEquationSeparate") == 0) { extern void* glBlendEquationSeparate; return &glBlendEquationSeparate; }
		if (strcmp(symbol, "glBlendEquationSeparatei") == 0) { extern void* glBlendEquationSeparatei; return &glBlendEquationSeparatei; }
		if (strcmp(symbol, "glBlendEquationi") == 0) { extern void* glBlendEquationi; return &glBlendEquationi; }
		if (strcmp(symbol, "glBlendFunc") == 0) { extern void* glBlendFunc; return &glBlendFunc; }
		if (strcmp(symbol, "glBlendFuncSeparate") == 0) { extern void* glBlendFuncSeparate; return &glBlendFuncSeparate; }
		if (strcmp(symbol, "glBlendFuncSeparatei") == 0) { extern void* glBlendFuncSeparatei; return &glBlendFuncSeparatei; }
		if (strcmp(symbol, "glBlendFunci") == 0) { extern void* glBlendFunci; return &glBlendFunci; }
		if (strcmp(symbol, "glBlitFramebuffer") == 0) { extern void* glBlitFramebuffer; return &glBlitFramebuffer; }
		if (strcmp(symbol, "glBufferData") == 0) { extern void* glBufferData; return &glBufferData; }
		if (strcmp(symbol, "glBufferSubData") == 0) { extern void* glBufferSubData; return &glBufferSubData; }
		if (strcmp(symbol, "glCheckFramebufferStatus") == 0) { extern void* glCheckFramebufferStatus; return &glCheckFramebufferStatus; }
		if (strcmp(symbol, "glClear") == 0) { extern void* glClear; return &glClear; }
		if (strcmp(symbol, "glClearBufferfi") == 0) { extern void* glClearBufferfi; return &glClearBufferfi; }
		if (strcmp(symbol, "glClearBufferfv") == 0) { extern void* glClearBufferfv; return &glClearBufferfv; }
		if (strcmp(symbol, "glClearBufferiv") == 0) { extern void* glClearBufferiv; return &glClearBufferiv; }
		if (strcmp(symbol, "glClearBufferuiv") == 0) { extern void* glClearBufferuiv; return &glClearBufferuiv; }
		if (strcmp(symbol, "glClearColor") == 0) { extern void* glClearColor; return &glClearColor; }
		if (strcmp(symbol, "glClearDepthf") == 0) { extern void* glClearDepthf; return &glClearDepthf; }
		if (strcmp(symbol, "glClearStencil") == 0) { extern void* glClearStencil; return &glClearStencil; }
		if (strcmp(symbol, "glClientWaitSync") == 0) { extern void* glClientWaitSync; return &glClientWaitSync; }
		if (strcmp(symbol, "glColorMask") == 0) { extern void* glColorMask; return &glColorMask; }
		if (strcmp(symbol, "glColorMaski") == 0) { extern void* glColorMaski; return &glColorMaski; }
		if (strcmp(symbol, "glCompileShader") == 0) { extern void* glCompileShader; return &glCompileShader; }
		if (strcmp(symbol, "glCompressedTexImage2D") == 0) { extern void* glCompressedTexImage2D; return &glCompressedTexImage2D; }
		if (strcmp(symbol, "glCompressedTexImage3D") == 0) { extern void* glCompressedTexImage3D; return &glCompressedTexImage3D; }
		if (strcmp(symbol, "glCompressedTexSubImage2D") == 0) { extern void* glCompressedTexSubImage2D; return &glCompressedTexSubImage2D; }
		if (strcmp(symbol, "glCompressedTexSubImage3D") == 0) { extern void* glCompressedTexSubImage3D; return &glCompressedTexSubImage3D; }
		if (strcmp(symbol, "glCopyBufferSubData") == 0) { extern void* glCopyBufferSubData; return &glCopyBufferSubData; }
		if (strcmp(symbol, "glCopyImageSubData") == 0) { extern void* glCopyImageSubData; return &glCopyImageSubData; }
		if (strcmp(symbol, "glCopyTexImage2D") == 0) { extern void* glCopyTexImage2D; return &glCopyTexImage2D; }
		if (strcmp(symbol, "glCopyTexSubImage2D") == 0) { extern void* glCopyTexSubImage2D; return &glCopyTexSubImage2D; }
		if (strcmp(symbol, "glCopyTexSubImage3D") == 0) { extern void* glCopyTexSubImage3D; return &glCopyTexSubImage3D; }
		if (strcmp(symbol, "glCreateProgram") == 0) { extern void* glCreateProgram; return &glCreateProgram; }
		if (strcmp(symbol, "glCreateShader") == 0) { extern void* glCreateShader; return &glCreateShader; }
		if (strcmp(symbol, "glCreateShaderProgramv") == 0) { extern void* glCreateShaderProgramv; return &glCreateShaderProgramv; }
		if (strcmp(symbol, "glCullFace") == 0) { extern void* glCullFace; return &glCullFace; }
		if (strcmp(symbol, "glDebugMessageCallback") == 0) { extern void* glDebugMessageCallback; return &glDebugMessageCallback; }
		if (strcmp(symbol, "glDebugMessageControl") == 0) { extern void* glDebugMessageControl; return &glDebugMessageControl; }
		if (strcmp(symbol, "glDebugMessageInsert") == 0) { extern void* glDebugMessageInsert; return &glDebugMessageInsert; }
		if (strcmp(symbol, "glDeleteBuffers") == 0) { extern void* glDeleteBuffers; return &glDeleteBuffers; }
		if (strcmp(symbol, "glDeleteFramebuffers") == 0) { extern void* glDeleteFramebuffers; return &glDeleteFramebuffers; }
		if (strcmp(symbol, "glDeleteProgram") == 0) { extern void* glDeleteProgram; return &glDeleteProgram; }
		if (strcmp(symbol, "glDeleteProgramPipelines") == 0) { extern void* glDeleteProgramPipelines; return &glDeleteProgramPipelines; }
		if (strcmp(symbol, "glDeleteQueries") == 0) { extern void* glDeleteQueries; return &glDeleteQueries; }
		if (strcmp(symbol, "glDeleteRenderbuffers") == 0) { extern void* glDeleteRenderbuffers; return &glDeleteRenderbuffers; }
		if (strcmp(symbol, "glDeleteSamplers") == 0) { extern void* glDeleteSamplers; return &glDeleteSamplers; }
		if (strcmp(symbol, "glDeleteShader") == 0) { extern void* glDeleteShader; return &glDeleteShader; }
		if (strcmp(symbol, "glDeleteSync") == 0) { extern void* glDeleteSync; return &glDeleteSync; }
		if (strcmp(symbol, "glDeleteTextures") == 0) { extern void* glDeleteTextures; return &glDeleteTextures; }
		if (strcmp(symbol, "glDeleteTransformFeedbacks") == 0) { extern void* glDeleteTransformFeedbacks; return &glDeleteTransformFeedbacks; }
		if (strcmp(symbol, "glDeleteVertexArrays") == 0) { extern void* glDeleteVertexArrays; return &glDeleteVertexArrays; }
		if (strcmp(symbol, "glDepthFunc") == 0) { extern void* glDepthFunc; return &glDepthFunc; }
		if (strcmp(symbol, "glDepthMask") == 0) { extern void* glDepthMask; return &glDepthMask; }
		if (strcmp(symbol, "glDepthRangef") == 0) { extern void* glDepthRangef; return &glDepthRangef; }
		if (strcmp(symbol, "glDetachShader") == 0) { extern void* glDetachShader; return &glDetachShader; }
		if (strcmp(symbol, "glDisable") == 0) { extern void* glDisable; return &glDisable; }
		if (strcmp(symbol, "glDisableVertexAttribArray") == 0) { extern void* glDisableVertexAttribArray; return &glDisableVertexAttribArray; }
		if (strcmp(symbol, "glDisablei") == 0) { extern void* glDisablei; return &glDisablei; }
		if (strcmp(symbol, "glDispatchCompute") == 0) { extern void* glDispatchCompute; return &glDispatchCompute; }
		if (strcmp(symbol, "glDispatchComputeIndirect") == 0) { extern void* glDispatchComputeIndirect; return &glDispatchComputeIndirect; }
		if (strcmp(symbol, "glDrawArrays") == 0) { extern void* glDrawArrays; return &glDrawArrays; }
		if (strcmp(symbol, "glDrawArraysIndirect") == 0) { extern void* glDrawArraysIndirect; return &glDrawArraysIndirect; }
		if (strcmp(symbol, "glDrawArraysInstanced") == 0) { extern void* glDrawArraysInstanced; return &glDrawArraysInstanced; }
		if (strcmp(symbol, "glDrawBuffers") == 0) { extern void* glDrawBuffers; return &glDrawBuffers; }
		if (strcmp(symbol, "glDrawElements") == 0) { extern void* glDrawElements; return &glDrawElements; }
		if (strcmp(symbol, "glDrawElementsBaseVertex") == 0) { extern void* glDrawElementsBaseVertex; return &glDrawElementsBaseVertex; }
		if (strcmp(symbol, "glDrawElementsIndirect") == 0) { extern void* glDrawElementsIndirect; return &glDrawElementsIndirect; }
		if (strcmp(symbol, "glDrawElementsInstanced") == 0) { extern void* glDrawElementsInstanced; return &glDrawElementsInstanced; }
		if (strcmp(symbol, "glDrawElementsInstancedBaseVertex") == 0) { extern void* glDrawElementsInstancedBaseVertex; return &glDrawElementsInstancedBaseVertex; }
		if (strcmp(symbol, "glDrawRangeElements") == 0) { extern void* glDrawRangeElements; return &glDrawRangeElements; }
		if (strcmp(symbol, "glDrawRangeElementsBaseVertex") == 0) { extern void* glDrawRangeElementsBaseVertex; return &glDrawRangeElementsBaseVertex; }
		if (strcmp(symbol, "glEnable") == 0) { extern void* glEnable; return &glEnable; }
		if (strcmp(symbol, "glEnableVertexAttribArray") == 0) { extern void* glEnableVertexAttribArray; return &glEnableVertexAttribArray; }
		if (strcmp(symbol, "glEnablei") == 0) { extern void* glEnablei; return &glEnablei; }
		if (strcmp(symbol, "glEndQuery") == 0) { extern void* glEndQuery; return &glEndQuery; }
		if (strcmp(symbol, "glEndTransformFeedback") == 0) { extern void* glEndTransformFeedback; return &glEndTransformFeedback; }
		if (strcmp(symbol, "glFenceSync") == 0) { extern void* glFenceSync; return &glFenceSync; }
		if (strcmp(symbol, "glFinish") == 0) { extern void* glFinish; return &glFinish; }
		if (strcmp(symbol, "glFlush") == 0) { extern void* glFlush; return &glFlush; }
		if (strcmp(symbol, "glFlushMappedBufferRange") == 0) { extern void* glFlushMappedBufferRange; return &glFlushMappedBufferRange; }
		if (strcmp(symbol, "glFramebufferParameteri") == 0) { extern void* glFramebufferParameteri; return &glFramebufferParameteri; }
		if (strcmp(symbol, "glFramebufferRenderbuffer") == 0) { extern void* glFramebufferRenderbuffer; return &glFramebufferRenderbuffer; }
		if (strcmp(symbol, "glFramebufferTexture") == 0) { extern void* glFramebufferTexture; return &glFramebufferTexture; }
		if (strcmp(symbol, "glFramebufferTexture2D") == 0) { extern void* glFramebufferTexture2D; return &glFramebufferTexture2D; }
		if (strcmp(symbol, "glFramebufferTextureLayer") == 0) { extern void* glFramebufferTextureLayer; return &glFramebufferTextureLayer; }
		if (strcmp(symbol, "glFrontFace") == 0) { extern void* glFrontFace; return &glFrontFace; }
		if (strcmp(symbol, "glGenBuffers") == 0) { extern void* glGenBuffers; return &glGenBuffers; }
		if (strcmp(symbol, "glGenFramebuffers") == 0) { extern void* glGenFramebuffers; return &glGenFramebuffers; }
		if (strcmp(symbol, "glGenProgramPipelines") == 0) { extern void* glGenProgramPipelines; return &glGenProgramPipelines; }
		if (strcmp(symbol, "glGenQueries") == 0) { extern void* glGenQueries; return &glGenQueries; }
		if (strcmp(symbol, "glGenRenderbuffers") == 0) { extern void* glGenRenderbuffers; return &glGenRenderbuffers; }
		if (strcmp(symbol, "glGenSamplers") == 0) { extern void* glGenSamplers; return &glGenSamplers; }
		if (strcmp(symbol, "glGenTextures") == 0) { extern void* glGenTextures; return &glGenTextures; }
		if (strcmp(symbol, "glGenTransformFeedbacks") == 0) { extern void* glGenTransformFeedbacks; return &glGenTransformFeedbacks; }
		if (strcmp(symbol, "glGenVertexArrays") == 0) { extern void* glGenVertexArrays; return &glGenVertexArrays; }
		if (strcmp(symbol, "glGenerateMipmap") == 0) { extern void* glGenerateMipmap; return &glGenerateMipmap; }
		if (strcmp(symbol, "glGetActiveAttrib") == 0) { extern void* glGetActiveAttrib; return &glGetActiveAttrib; }
		if (strcmp(symbol, "glGetActiveUniform") == 0) { extern void* glGetActiveUniform; return &glGetActiveUniform; }
		if (strcmp(symbol, "glGetActiveUniformBlockName") == 0) { extern void* glGetActiveUniformBlockName; return &glGetActiveUniformBlockName; }
		if (strcmp(symbol, "glGetActiveUniformBlockiv") == 0) { extern void* glGetActiveUniformBlockiv; return &glGetActiveUniformBlockiv; }
		if (strcmp(symbol, "glGetActiveUniformsiv") == 0) { extern void* glGetActiveUniformsiv; return &glGetActiveUniformsiv; }
		if (strcmp(symbol, "glGetAttachedShaders") == 0) { extern void* glGetAttachedShaders; return &glGetAttachedShaders; }
		if (strcmp(symbol, "glGetAttribLocation") == 0) { extern void* glGetAttribLocation; return &glGetAttribLocation; }
		if (strcmp(symbol, "glGetBooleani_v") == 0) { extern void* glGetBooleani_v; return &glGetBooleani_v; }
		if (strcmp(symbol, "glGetBooleanv") == 0) { extern void* glGetBooleanv; return &glGetBooleanv; }
		if (strcmp(symbol, "glGetBufferParameteri64v") == 0) { extern void* glGetBufferParameteri64v; return &glGetBufferParameteri64v; }
		if (strcmp(symbol, "glGetBufferParameteriv") == 0) { extern void* glGetBufferParameteriv; return &glGetBufferParameteriv; }
		if (strcmp(symbol, "glGetBufferPointerv") == 0) { extern void* glGetBufferPointerv; return &glGetBufferPointerv; }
		if (strcmp(symbol, "glGetDebugMessageLog") == 0) { extern void* glGetDebugMessageLog; return &glGetDebugMessageLog; }
		if (strcmp(symbol, "glGetError") == 0) { extern void* glGetError; return &glGetError; }
		if (strcmp(symbol, "glGetFloatv") == 0) { extern void* glGetFloatv; return &glGetFloatv; }
		if (strcmp(symbol, "glGetFragDataLocation") == 0) { extern void* glGetFragDataLocation; return &glGetFragDataLocation; }
		if (strcmp(symbol, "glGetFramebufferAttachmentParameteriv") == 0) { extern void* glGetFramebufferAttachmentParameteriv; return &glGetFramebufferAttachmentParameteriv; }
		if (strcmp(symbol, "glGetFramebufferParameteriv") == 0) { extern void* glGetFramebufferParameteriv; return &glGetFramebufferParameteriv; }
		if (strcmp(symbol, "glGetGraphicsResetStatus") == 0) { extern void* glGetGraphicsResetStatus; return &glGetGraphicsResetStatus; }
		if (strcmp(symbol, "glGetInteger64i_v") == 0) { extern void* glGetInteger64i_v; return &glGetInteger64i_v; }
		if (strcmp(symbol, "glGetInteger64v") == 0) { extern void* glGetInteger64v; return &glGetInteger64v; }
		if (strcmp(symbol, "glGetIntegeri_v") == 0) { extern void* glGetIntegeri_v; return &glGetIntegeri_v; }
		if (strcmp(symbol, "glGetIntegerv") == 0) { extern void* glGetIntegerv; return &glGetIntegerv; }
		if (strcmp(symbol, "glGetInternalformativ") == 0) { extern void* glGetInternalformativ; return &glGetInternalformativ; }
		if (strcmp(symbol, "glGetMultisamplefv") == 0) { extern void* glGetMultisamplefv; return &glGetMultisamplefv; }
		if (strcmp(symbol, "glGetObjectLabel") == 0) { extern void* glGetObjectLabel; return &glGetObjectLabel; }
		if (strcmp(symbol, "glGetObjectPtrLabel") == 0) { extern void* glGetObjectPtrLabel; return &glGetObjectPtrLabel; }
		if (strcmp(symbol, "glGetPointerv") == 0) { extern void* glGetPointerv; return &glGetPointerv; }
		if (strcmp(symbol, "glGetProgramBinary") == 0) { extern void* glGetProgramBinary; return &glGetProgramBinary; }
		if (strcmp(symbol, "glGetProgramInfoLog") == 0) { extern void* glGetProgramInfoLog; return &glGetProgramInfoLog; }
		if (strcmp(symbol, "glGetProgramInterfaceiv") == 0) { extern void* glGetProgramInterfaceiv; return &glGetProgramInterfaceiv; }
		if (strcmp(symbol, "glGetProgramPipelineInfoLog") == 0) { extern void* glGetProgramPipelineInfoLog; return &glGetProgramPipelineInfoLog; }
		if (strcmp(symbol, "glGetProgramPipelineiv") == 0) { extern void* glGetProgramPipelineiv; return &glGetProgramPipelineiv; }
		if (strcmp(symbol, "glGetProgramResourceIndex") == 0) { extern void* glGetProgramResourceIndex; return &glGetProgramResourceIndex; }
		if (strcmp(symbol, "glGetProgramResourceLocation") == 0) { extern void* glGetProgramResourceLocation; return &glGetProgramResourceLocation; }
		if (strcmp(symbol, "glGetProgramResourceName") == 0) { extern void* glGetProgramResourceName; return &glGetProgramResourceName; }
		if (strcmp(symbol, "glGetProgramResourceiv") == 0) { extern void* glGetProgramResourceiv; return &glGetProgramResourceiv; }
		if (strcmp(symbol, "glGetProgramiv") == 0) { extern void* glGetProgramiv; return &glGetProgramiv; }
		if (strcmp(symbol, "glGetQueryObjectuiv") == 0) { extern void* glGetQueryObjectuiv; return &glGetQueryObjectuiv; }
		if (strcmp(symbol, "glGetQueryiv") == 0) { extern void* glGetQueryiv; return &glGetQueryiv; }
		if (strcmp(symbol, "glGetRenderbufferParameteriv") == 0) { extern void* glGetRenderbufferParameteriv; return &glGetRenderbufferParameteriv; }
		if (strcmp(symbol, "glGetSamplerParameterIiv") == 0) { extern void* glGetSamplerParameterIiv; return &glGetSamplerParameterIiv; }
		if (strcmp(symbol, "glGetSamplerParameterIuiv") == 0) { extern void* glGetSamplerParameterIuiv; return &glGetSamplerParameterIuiv; }
		if (strcmp(symbol, "glGetSamplerParameterfv") == 0) { extern void* glGetSamplerParameterfv; return &glGetSamplerParameterfv; }
		if (strcmp(symbol, "glGetSamplerParameteriv") == 0) { extern void* glGetSamplerParameteriv; return &glGetSamplerParameteriv; }
		if (strcmp(symbol, "glGetShaderInfoLog") == 0) { extern void* glGetShaderInfoLog; return &glGetShaderInfoLog; }
		if (strcmp(symbol, "glGetShaderPrecisionFormat") == 0) { extern void* glGetShaderPrecisionFormat; return &glGetShaderPrecisionFormat; }
		if (strcmp(symbol, "glGetShaderSource") == 0) { extern void* glGetShaderSource; return &glGetShaderSource; }
		if (strcmp(symbol, "glGetShaderiv") == 0) { extern void* glGetShaderiv; return &glGetShaderiv; }
		if (strcmp(symbol, "glGetString") == 0) { extern void* glGetString; return &glGetString; }
		if (strcmp(symbol, "glGetStringi") == 0) { extern void* glGetStringi; return &glGetStringi; }
		if (strcmp(symbol, "glGetSynciv") == 0) { extern void* glGetSynciv; return &glGetSynciv; }
		if (strcmp(symbol, "glGetTexLevelParameterfv") == 0) { extern void* glGetTexLevelParameterfv; return &glGetTexLevelParameterfv; }
		if (strcmp(symbol, "glGetTexLevelParameteriv") == 0) { extern void* glGetTexLevelParameteriv; return &glGetTexLevelParameteriv; }
		if (strcmp(symbol, "glGetTexParameterIiv") == 0) { extern void* glGetTexParameterIiv; return &glGetTexParameterIiv; }
		if (strcmp(symbol, "glGetTexParameterIuiv") == 0) { extern void* glGetTexParameterIuiv; return &glGetTexParameterIuiv; }
		if (strcmp(symbol, "glGetTexParameterfv") == 0) { extern void* glGetTexParameterfv; return &glGetTexParameterfv; }
		if (strcmp(symbol, "glGetTexParameteriv") == 0) { extern void* glGetTexParameteriv; return &glGetTexParameteriv; }
		if (strcmp(symbol, "glGetTransformFeedbackVarying") == 0) { extern void* glGetTransformFeedbackVarying; return &glGetTransformFeedbackVarying; }
		if (strcmp(symbol, "glGetUniformBlockIndex") == 0) { extern void* glGetUniformBlockIndex; return &glGetUniformBlockIndex; }
		if (strcmp(symbol, "glGetUniformIndices") == 0) { extern void* glGetUniformIndices; return &glGetUniformIndices; }
		if (strcmp(symbol, "glGetUniformLocation") == 0) { extern void* glGetUniformLocation; return &glGetUniformLocation; }
		if (strcmp(symbol, "glGetUniformfv") == 0) { extern void* glGetUniformfv; return &glGetUniformfv; }
		if (strcmp(symbol, "glGetUniformiv") == 0) { extern void* glGetUniformiv; return &glGetUniformiv; }
		if (strcmp(symbol, "glGetUniformuiv") == 0) { extern void* glGetUniformuiv; return &glGetUniformuiv; }
		if (strcmp(symbol, "glGetVertexAttribIiv") == 0) { extern void* glGetVertexAttribIiv; return &glGetVertexAttribIiv; }
		if (strcmp(symbol, "glGetVertexAttribIuiv") == 0) { extern void* glGetVertexAttribIuiv; return &glGetVertexAttribIuiv; }
		if (strcmp(symbol, "glGetVertexAttribPointerv") == 0) { extern void* glGetVertexAttribPointerv; return &glGetVertexAttribPointerv; }
		if (strcmp(symbol, "glGetVertexAttribfv") == 0) { extern void* glGetVertexAttribfv; return &glGetVertexAttribfv; }
		if (strcmp(symbol, "glGetVertexAttribiv") == 0) { extern void* glGetVertexAttribiv; return &glGetVertexAttribiv; }
		if (strcmp(symbol, "glGetnUniformfv") == 0) { extern void* glGetnUniformfv; return &glGetnUniformfv; }
		if (strcmp(symbol, "glGetnUniformiv") == 0) { extern void* glGetnUniformiv; return &glGetnUniformiv; }
		if (strcmp(symbol, "glGetnUniformuiv") == 0) { extern void* glGetnUniformuiv; return &glGetnUniformuiv; }
		if (strcmp(symbol, "glHint") == 0) { extern void* glHint; return &glHint; }
		if (strcmp(symbol, "glInvalidateFramebuffer") == 0) { extern void* glInvalidateFramebuffer; return &glInvalidateFramebuffer; }
		if (strcmp(symbol, "glInvalidateSubFramebuffer") == 0) { extern void* glInvalidateSubFramebuffer; return &glInvalidateSubFramebuffer; }
		if (strcmp(symbol, "glIsBuffer") == 0) { extern void* glIsBuffer; return &glIsBuffer; }
		if (strcmp(symbol, "glIsEnabled") == 0) { extern void* glIsEnabled; return &glIsEnabled; }
		if (strcmp(symbol, "glIsEnabledi") == 0) { extern void* glIsEnabledi; return &glIsEnabledi; }
		if (strcmp(symbol, "glIsFramebuffer") == 0) { extern void* glIsFramebuffer; return &glIsFramebuffer; }
		if (strcmp(symbol, "glIsProgram") == 0) { extern void* glIsProgram; return &glIsProgram; }
		if (strcmp(symbol, "glIsProgramPipeline") == 0) { extern void* glIsProgramPipeline; return &glIsProgramPipeline; }
		if (strcmp(symbol, "glIsQuery") == 0) { extern void* glIsQuery; return &glIsQuery; }
		if (strcmp(symbol, "glIsRenderbuffer") == 0) { extern void* glIsRenderbuffer; return &glIsRenderbuffer; }
		if (strcmp(symbol, "glIsSampler") == 0) { extern void* glIsSampler; return &glIsSampler; }
		if (strcmp(symbol, "glIsShader") == 0) { extern void* glIsShader; return &glIsShader; }
		if (strcmp(symbol, "glIsSync") == 0) { extern void* glIsSync; return &glIsSync; }
		if (strcmp(symbol, "glIsTexture") == 0) { extern void* glIsTexture; return &glIsTexture; }
		if (strcmp(symbol, "glIsTransformFeedback") == 0) { extern void* glIsTransformFeedback; return &glIsTransformFeedback; }
		if (strcmp(symbol, "glIsVertexArray") == 0) { extern void* glIsVertexArray; return &glIsVertexArray; }
		if (strcmp(symbol, "glLineWidth") == 0) { extern void* glLineWidth; return &glLineWidth; }
		if (strcmp(symbol, "glLinkProgram") == 0) { extern void* glLinkProgram; return &glLinkProgram; }
		if (strcmp(symbol, "glMapBufferRange") == 0) { extern void* glMapBufferRange; return &glMapBufferRange; }
		if (strcmp(symbol, "glMemoryBarrier") == 0) { extern void* glMemoryBarrier; return &glMemoryBarrier; }
		if (strcmp(symbol, "glMemoryBarrierByRegion") == 0) { extern void* glMemoryBarrierByRegion; return &glMemoryBarrierByRegion; }
		if (strcmp(symbol, "glMinSampleShading") == 0) { extern void* glMinSampleShading; return &glMinSampleShading; }
		if (strcmp(symbol, "glObjectLabel") == 0) { extern void* glObjectLabel; return &glObjectLabel; }
		if (strcmp(symbol, "glObjectPtrLabel") == 0) { extern void* glObjectPtrLabel; return &glObjectPtrLabel; }
		if (strcmp(symbol, "glPatchParameteri") == 0) { extern void* glPatchParameteri; return &glPatchParameteri; }
		if (strcmp(symbol, "glPauseTransformFeedback") == 0) { extern void* glPauseTransformFeedback; return &glPauseTransformFeedback; }
		if (strcmp(symbol, "glPixelStorei") == 0) { extern void* glPixelStorei; return &glPixelStorei; }
		if (strcmp(symbol, "glPolygonOffset") == 0) { extern void* glPolygonOffset; return &glPolygonOffset; }
		if (strcmp(symbol, "glPopDebugGroup") == 0) { extern void* glPopDebugGroup; return &glPopDebugGroup; }
		if (strcmp(symbol, "glPrimitiveBoundingBox") == 0) { extern void* glPrimitiveBoundingBox; return &glPrimitiveBoundingBox; }
		if (strcmp(symbol, "glProgramBinary") == 0) { extern void* glProgramBinary; return &glProgramBinary; }
		if (strcmp(symbol, "glProgramParameteri") == 0) { extern void* glProgramParameteri; return &glProgramParameteri; }
		if (strcmp(symbol, "glProgramUniform1f") == 0) { extern void* glProgramUniform1f; return &glProgramUniform1f; }
		if (strcmp(symbol, "glProgramUniform1fv") == 0) { extern void* glProgramUniform1fv; return &glProgramUniform1fv; }
		if (strcmp(symbol, "glProgramUniform1i") == 0) { extern void* glProgramUniform1i; return &glProgramUniform1i; }
		if (strcmp(symbol, "glProgramUniform1iv") == 0) { extern void* glProgramUniform1iv; return &glProgramUniform1iv; }
		if (strcmp(symbol, "glProgramUniform1ui") == 0) { extern void* glProgramUniform1ui; return &glProgramUniform1ui; }
		if (strcmp(symbol, "glProgramUniform1uiv") == 0) { extern void* glProgramUniform1uiv; return &glProgramUniform1uiv; }
		if (strcmp(symbol, "glProgramUniform2f") == 0) { extern void* glProgramUniform2f; return &glProgramUniform2f; }
		if (strcmp(symbol, "glProgramUniform2fv") == 0) { extern void* glProgramUniform2fv; return &glProgramUniform2fv; }
		if (strcmp(symbol, "glProgramUniform2i") == 0) { extern void* glProgramUniform2i; return &glProgramUniform2i; }
		if (strcmp(symbol, "glProgramUniform2iv") == 0) { extern void* glProgramUniform2iv; return &glProgramUniform2iv; }
		if (strcmp(symbol, "glProgramUniform2ui") == 0) { extern void* glProgramUniform2ui; return &glProgramUniform2ui; }
		if (strcmp(symbol, "glProgramUniform2uiv") == 0) { extern void* glProgramUniform2uiv; return &glProgramUniform2uiv; }
		if (strcmp(symbol, "glProgramUniform3f") == 0) { extern void* glProgramUniform3f; return &glProgramUniform3f; }
		if (strcmp(symbol, "glProgramUniform3fv") == 0) { extern void* glProgramUniform3fv; return &glProgramUniform3fv; }
		if (strcmp(symbol, "glProgramUniform3i") == 0) { extern void* glProgramUniform3i; return &glProgramUniform3i; }
		if (strcmp(symbol, "glProgramUniform3iv") == 0) { extern void* glProgramUniform3iv; return &glProgramUniform3iv; }
		if (strcmp(symbol, "glProgramUniform3ui") == 0) { extern void* glProgramUniform3ui; return &glProgramUniform3ui; }
		if (strcmp(symbol, "glProgramUniform3uiv") == 0) { extern void* glProgramUniform3uiv; return &glProgramUniform3uiv; }
		if (strcmp(symbol, "glProgramUniform4f") == 0) { extern void* glProgramUniform4f; return &glProgramUniform4f; }
		if (strcmp(symbol, "glProgramUniform4fv") == 0) { extern void* glProgramUniform4fv; return &glProgramUniform4fv; }
		if (strcmp(symbol, "glProgramUniform4i") == 0) { extern void* glProgramUniform4i; return &glProgramUniform4i; }
		if (strcmp(symbol, "glProgramUniform4iv") == 0) { extern void* glProgramUniform4iv; return &glProgramUniform4iv; }
		if (strcmp(symbol, "glProgramUniform4ui") == 0) { extern void* glProgramUniform4ui; return &glProgramUniform4ui; }
		if (strcmp(symbol, "glProgramUniform4uiv") == 0) { extern void* glProgramUniform4uiv; return &glProgramUniform4uiv; }
		if (strcmp(symbol, "glProgramUniformMatrix2fv") == 0) { extern void* glProgramUniformMatrix2fv; return &glProgramUniformMatrix2fv; }
		if (strcmp(symbol, "glProgramUniformMatrix2x3fv") == 0) { extern void* glProgramUniformMatrix2x3fv; return &glProgramUniformMatrix2x3fv; }
		if (strcmp(symbol, "glProgramUniformMatrix2x4fv") == 0) { extern void* glProgramUniformMatrix2x4fv; return &glProgramUniformMatrix2x4fv; }
		if (strcmp(symbol, "glProgramUniformMatrix3fv") == 0) { extern void* glProgramUniformMatrix3fv; return &glProgramUniformMatrix3fv; }
		if (strcmp(symbol, "glProgramUniformMatrix3x2fv") == 0) { extern void* glProgramUniformMatrix3x2fv; return &glProgramUniformMatrix3x2fv; }
		if (strcmp(symbol, "glProgramUniformMatrix3x4fv") == 0) { extern void* glProgramUniformMatrix3x4fv; return &glProgramUniformMatrix3x4fv; }
		if (strcmp(symbol, "glProgramUniformMatrix4fv") == 0) { extern void* glProgramUniformMatrix4fv; return &glProgramUniformMatrix4fv; }
		if (strcmp(symbol, "glProgramUniformMatrix4x2fv") == 0) { extern void* glProgramUniformMatrix4x2fv; return &glProgramUniformMatrix4x2fv; }
		if (strcmp(symbol, "glProgramUniformMatrix4x3fv") == 0) { extern void* glProgramUniformMatrix4x3fv; return &glProgramUniformMatrix4x3fv; }
		if (strcmp(symbol, "glPushDebugGroup") == 0) { extern void* glPushDebugGroup; return &glPushDebugGroup; }
		if (strcmp(symbol, "glReadBuffer") == 0) { extern void* glReadBuffer; return &glReadBuffer; }
		if (strcmp(symbol, "glReadPixels") == 0) { extern void* glReadPixels; return &glReadPixels; }
		if (strcmp(symbol, "glReadnPixels") == 0) { extern void* glReadnPixels; return &glReadnPixels; }
		if (strcmp(symbol, "glReleaseShaderCompiler") == 0) { extern void* glReleaseShaderCompiler; return &glReleaseShaderCompiler; }
		if (strcmp(symbol, "glRenderbufferStorage") == 0) { extern void* glRenderbufferStorage; return &glRenderbufferStorage; }
		if (strcmp(symbol, "glRenderbufferStorageMultisample") == 0) { extern void* glRenderbufferStorageMultisample; return &glRenderbufferStorageMultisample; }
		if (strcmp(symbol, "glResumeTransformFeedback") == 0) { extern void* glResumeTransformFeedback; return &glResumeTransformFeedback; }
		if (strcmp(symbol, "glSampleCoverage") == 0) { extern void* glSampleCoverage; return &glSampleCoverage; }
		if (strcmp(symbol, "glSampleMaski") == 0) { extern void* glSampleMaski; return &glSampleMaski; }
		if (strcmp(symbol, "glSamplerParameterIiv") == 0) { extern void* glSamplerParameterIiv; return &glSamplerParameterIiv; }
		if (strcmp(symbol, "glSamplerParameterIuiv") == 0) { extern void* glSamplerParameterIuiv; return &glSamplerParameterIuiv; }
		if (strcmp(symbol, "glSamplerParameterf") == 0) { extern void* glSamplerParameterf; return &glSamplerParameterf; }
		if (strcmp(symbol, "glSamplerParameterfv") == 0) { extern void* glSamplerParameterfv; return &glSamplerParameterfv; }
		if (strcmp(symbol, "glSamplerParameteri") == 0) { extern void* glSamplerParameteri; return &glSamplerParameteri; }
		if (strcmp(symbol, "glSamplerParameteriv") == 0) { extern void* glSamplerParameteriv; return &glSamplerParameteriv; }
		if (strcmp(symbol, "glScissor") == 0) { extern void* glScissor; return &glScissor; }
		if (strcmp(symbol, "glShaderBinary") == 0) { extern void* glShaderBinary; return &glShaderBinary; }
		if (strcmp(symbol, "glShaderSource") == 0) { extern void* glShaderSource; return &glShaderSource; }
		if (strcmp(symbol, "glStencilFunc") == 0) { extern void* glStencilFunc; return &glStencilFunc; }
		if (strcmp(symbol, "glStencilFuncSeparate") == 0) { extern void* glStencilFuncSeparate; return &glStencilFuncSeparate; }
		if (strcmp(symbol, "glStencilMask") == 0) { extern void* glStencilMask; return &glStencilMask; }
		if (strcmp(symbol, "glStencilMaskSeparate") == 0) { extern void* glStencilMaskSeparate; return &glStencilMaskSeparate; }
		if (strcmp(symbol, "glStencilOp") == 0) { extern void* glStencilOp; return &glStencilOp; }
		if (strcmp(symbol, "glStencilOpSeparate") == 0) { extern void* glStencilOpSeparate; return &glStencilOpSeparate; }
		if (strcmp(symbol, "glTexBuffer") == 0) { extern void* glTexBuffer; return &glTexBuffer; }
		if (strcmp(symbol, "glTexBufferRange") == 0) { extern void* glTexBufferRange; return &glTexBufferRange; }
		if (strcmp(symbol, "glTexImage2D") == 0) { extern void* glTexImage2D; return &glTexImage2D; }
		if (strcmp(symbol, "glTexImage3D") == 0) { extern void* glTexImage3D; return &glTexImage3D; }
		if (strcmp(symbol, "glTexParameterIiv") == 0) { extern void* glTexParameterIiv; return &glTexParameterIiv; }
		if (strcmp(symbol, "glTexParameterIuiv") == 0) { extern void* glTexParameterIuiv; return &glTexParameterIuiv; }
		if (strcmp(symbol, "glTexParameterf") == 0) { extern void* glTexParameterf; return &glTexParameterf; }
		if (strcmp(symbol, "glTexParameterfv") == 0) { extern void* glTexParameterfv; return &glTexParameterfv; }
		if (strcmp(symbol, "glTexParameteri") == 0) { extern void* glTexParameteri; return &glTexParameteri; }
		if (strcmp(symbol, "glTexParameteriv") == 0) { extern void* glTexParameteriv; return &glTexParameteriv; }
		if (strcmp(symbol, "glTexStorage2D") == 0) { extern void* glTexStorage2D; return &glTexStorage2D; }
		if (strcmp(symbol, "glTexStorage2DMultisample") == 0) { extern void* glTexStorage2DMultisample; return &glTexStorage2DMultisample; }
		if (strcmp(symbol, "glTexStorage3D") == 0) { extern void* glTexStorage3D; return &glTexStorage3D; }
		if (strcmp(symbol, "glTexStorage3DMultisample") == 0) { extern void* glTexStorage3DMultisample; return &glTexStorage3DMultisample; }
		if (strcmp(symbol, "glTexSubImage2D") == 0) { extern void* glTexSubImage2D; return &glTexSubImage2D; }
		if (strcmp(symbol, "glTexSubImage3D") == 0) { extern void* glTexSubImage3D; return &glTexSubImage3D; }
		if (strcmp(symbol, "glTransformFeedbackVaryings") == 0) { extern void* glTransformFeedbackVaryings; return &glTransformFeedbackVaryings; }
		if (strcmp(symbol, "glUniform1f") == 0) { extern void* glUniform1f; return &glUniform1f; }
		if (strcmp(symbol, "glUniform1fv") == 0) { extern void* glUniform1fv; return &glUniform1fv; }
		if (strcmp(symbol, "glUniform1i") == 0) { extern void* glUniform1i; return &glUniform1i; }
		if (strcmp(symbol, "glUniform1iv") == 0) { extern void* glUniform1iv; return &glUniform1iv; }
		if (strcmp(symbol, "glUniform1ui") == 0) { extern void* glUniform1ui; return &glUniform1ui; }
		if (strcmp(symbol, "glUniform1uiv") == 0) { extern void* glUniform1uiv; return &glUniform1uiv; }
		if (strcmp(symbol, "glUniform2f") == 0) { extern void* glUniform2f; return &glUniform2f; }
		if (strcmp(symbol, "glUniform2fv") == 0) { extern void* glUniform2fv; return &glUniform2fv; }
		if (strcmp(symbol, "glUniform2i") == 0) { extern void* glUniform2i; return &glUniform2i; }
		if (strcmp(symbol, "glUniform2iv") == 0) { extern void* glUniform2iv; return &glUniform2iv; }
		if (strcmp(symbol, "glUniform2ui") == 0) { extern void* glUniform2ui; return &glUniform2ui; }
		if (strcmp(symbol, "glUniform2uiv") == 0) { extern void* glUniform2uiv; return &glUniform2uiv; }
		if (strcmp(symbol, "glUniform3f") == 0) { extern void* glUniform3f; return &glUniform3f; }
		if (strcmp(symbol, "glUniform3fv") == 0) { extern void* glUniform3fv; return &glUniform3fv; }
		if (strcmp(symbol, "glUniform3i") == 0) { extern void* glUniform3i; return &glUniform3i; }
		if (strcmp(symbol, "glUniform3iv") == 0) { extern void* glUniform3iv; return &glUniform3iv; }
		if (strcmp(symbol, "glUniform3ui") == 0) { extern void* glUniform3ui; return &glUniform3ui; }
		if (strcmp(symbol, "glUniform3uiv") == 0) { extern void* glUniform3uiv; return &glUniform3uiv; }
		if (strcmp(symbol, "glUniform4f") == 0) { extern void* glUniform4f; return &glUniform4f; }
		if (strcmp(symbol, "glUniform4fv") == 0) { extern void* glUniform4fv; return &glUniform4fv; }
		if (strcmp(symbol, "glUniform4i") == 0) { extern void* glUniform4i; return &glUniform4i; }
		if (strcmp(symbol, "glUniform4iv") == 0) { extern void* glUniform4iv; return &glUniform4iv; }
		if (strcmp(symbol, "glUniform4ui") == 0) { extern void* glUniform4ui; return &glUniform4ui; }
		if (strcmp(symbol, "glUniform4uiv") == 0) { extern void* glUniform4uiv; return &glUniform4uiv; }
		if (strcmp(symbol, "glUniformBlockBinding") == 0) { extern void* glUniformBlockBinding; return &glUniformBlockBinding; }
		if (strcmp(symbol, "glUniformMatrix2fv") == 0) { extern void* glUniformMatrix2fv; return &glUniformMatrix2fv; }
		if (strcmp(symbol, "glUniformMatrix2x3fv") == 0) { extern void* glUniformMatrix2x3fv; return &glUniformMatrix2x3fv; }
		if (strcmp(symbol, "glUniformMatrix2x4fv") == 0) { extern void* glUniformMatrix2x4fv; return &glUniformMatrix2x4fv; }
		if (strcmp(symbol, "glUniformMatrix3fv") == 0) { extern void* glUniformMatrix3fv; return &glUniformMatrix3fv; }
		if (strcmp(symbol, "glUniformMatrix3x2fv") == 0) { extern void* glUniformMatrix3x2fv; return &glUniformMatrix3x2fv; }
		if (strcmp(symbol, "glUniformMatrix3x4fv") == 0) { extern void* glUniformMatrix3x4fv; return &glUniformMatrix3x4fv; }
		if (strcmp(symbol, "glUniformMatrix4fv") == 0) { extern void* glUniformMatrix4fv; return &glUniformMatrix4fv; }
		if (strcmp(symbol, "glUniformMatrix4x2fv") == 0) { extern void* glUniformMatrix4x2fv; return &glUniformMatrix4x2fv; }
		if (strcmp(symbol, "glUniformMatrix4x3fv") == 0) { extern void* glUniformMatrix4x3fv; return &glUniformMatrix4x3fv; }
		if (strcmp(symbol, "glUnmapBuffer") == 0) { extern void* glUnmapBuffer; return &glUnmapBuffer; }
		if (strcmp(symbol, "glUseProgram") == 0) { extern void* glUseProgram; return &glUseProgram; }
		if (strcmp(symbol, "glUseProgramStages") == 0) { extern void* glUseProgramStages; return &glUseProgramStages; }
		if (strcmp(symbol, "glValidateProgram") == 0) { extern void* glValidateProgram; return &glValidateProgram; }
		if (strcmp(symbol, "glValidateProgramPipeline") == 0) { extern void* glValidateProgramPipeline; return &glValidateProgramPipeline; }
		if (strcmp(symbol, "glVertexAttrib1f") == 0) { extern void* glVertexAttrib1f; return &glVertexAttrib1f; }
		if (strcmp(symbol, "glVertexAttrib1fv") == 0) { extern void* glVertexAttrib1fv; return &glVertexAttrib1fv; }
		if (strcmp(symbol, "glVertexAttrib2f") == 0) { extern void* glVertexAttrib2f; return &glVertexAttrib2f; }
		if (strcmp(symbol, "glVertexAttrib2fv") == 0) { extern void* glVertexAttrib2fv; return &glVertexAttrib2fv; }
		if (strcmp(symbol, "glVertexAttrib3f") == 0) { extern void* glVertexAttrib3f; return &glVertexAttrib3f; }
		if (strcmp(symbol, "glVertexAttrib3fv") == 0) { extern void* glVertexAttrib3fv; return &glVertexAttrib3fv; }
		if (strcmp(symbol, "glVertexAttrib4f") == 0) { extern void* glVertexAttrib4f; return &glVertexAttrib4f; }
		if (strcmp(symbol, "glVertexAttrib4fv") == 0) { extern void* glVertexAttrib4fv; return &glVertexAttrib4fv; }
		if (strcmp(symbol, "glVertexAttribBinding") == 0) { extern void* glVertexAttribBinding; return &glVertexAttribBinding; }
		if (strcmp(symbol, "glVertexAttribDivisor") == 0) { extern void* glVertexAttribDivisor; return &glVertexAttribDivisor; }
		if (strcmp(symbol, "glVertexAttribFormat") == 0) { extern void* glVertexAttribFormat; return &glVertexAttribFormat; }
		if (strcmp(symbol, "glVertexAttribI4i") == 0) { extern void* glVertexAttribI4i; return &glVertexAttribI4i; }
		if (strcmp(symbol, "glVertexAttribI4iv") == 0) { extern void* glVertexAttribI4iv; return &glVertexAttribI4iv; }
		if (strcmp(symbol, "glVertexAttribI4ui") == 0) { extern void* glVertexAttribI4ui; return &glVertexAttribI4ui; }
		if (strcmp(symbol, "glVertexAttribI4uiv") == 0) { extern void* glVertexAttribI4uiv; return &glVertexAttribI4uiv; }
		if (strcmp(symbol, "glVertexAttribIFormat") == 0) { extern void* glVertexAttribIFormat; return &glVertexAttribIFormat; }
		if (strcmp(symbol, "glVertexAttribIPointer") == 0) { extern void* glVertexAttribIPointer; return &glVertexAttribIPointer; }
		if (strcmp(symbol, "glVertexAttribPointer") == 0) { extern void* glVertexAttribPointer; return &glVertexAttribPointer; }
		if (strcmp(symbol, "glVertexBindingDivisor") == 0) { extern void* glVertexBindingDivisor; return &glVertexBindingDivisor; }
		if (strcmp(symbol, "glViewport") == 0) { extern void* glViewport; return &glViewport; }
		if (strcmp(symbol, "glWaitSync") == 0) { extern void* glWaitSync; return &glWaitSync; }
	}
	fprintf(stderr, "(dlsym) WARNING: failed for symbol %s\n", symbol);	return stub_dlsym(handle, symbol);
}


int dladdr(const void *handle, Dl_info *info)
{
    fprintf(stderr, "(dladdr) handle=\"%p\"\n", handle);
    return stub_dladdr(handle, info);
}

